import { Injectable } from '@angular/core';

export type PoemLanguage = 'bikolano' | 'english';

export interface Poem {
  id: number;
  title: string;
  author: string;
  excerpt: string[];
  lines: string[];
  mood: string;
  accentColor: string;
  language: PoemLanguage;
  translationLines?: string[];
}

export interface PoemContext {
  poem: Poem;
  prev: Poem | null;
  next: Poem | null;
  stanzas: string[][];
}

@Injectable({ providedIn: 'root' })
export class PoemsService {
  private readonly poems: ReadonlyArray<Poem> = [
    {
      id: 1,
      title: 'An Barkong Nag-abot',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Sa tahaw kan gabing puno nin kadikloman,', 'May barkong nag-abot sa tahimik na baybayan;'],
      mood: 'Reflective',
      accentColor: '#2E8B57',
      language: 'bikolano',
      lines: [
        'Sa tahaw kan gabing puno nin kadikloman,',
        'May barkong nag-abot sa tahimik na baybayan;',
        'Nagdanay ako sa harani kan pantalan,',
        'Dai aram kun biyaya o panibagong kasakitan.',
        '',
        'Dakol nang bagyo an nag-agi sa karagatan,',
        'Dakol nang saad an tinabunan nin kalipatan;',
        'Dakol nang pusong ginadan nin kasalanan,',
        'Asin dakol nang mata an napuno nin kalungkutan.',
        '',
        'Nung marungog ko an saimong dating kaagihan,',
        'Napuno ako nin dakulang pagduduman;',
        'Ta may mga taong naglalaro sa paglaoman,',
        'Asin nag-iiwan nin bakas na dai malipatan.',
        '',
        'Kaya ako nagdanay sa tahaw kan pantalan,',
        'Dai nagdadalagan sa bagong kapalaran;',
        'Mas marhay nang magbantay sa kalayuan,',
        'Kaysa mahulog naman sa dating kasakitan.',
        '',
        'Pero bako an hangin an nagpoon nin kahadean,',
        'Bako man an alon sa tahaw kan baybayan;',
        'Sa gabing tahimik asin puno nin kahiloman,',
        'Ikaw an nagtao kan pinakaunang kahadean.',
        '',
        'Sarong simpleng pagbati na may kalambingan,',
        'Wara nin pilit, wara nin kapalaluan;',
        'Pero sa puso kong puno nin pagduduman,',
        'Nagtanom iyan nin munting paglaoman.',
        '',
        'Ipinahiling ko saimo an sakuyang mga gibuhon,',
        'Mga proyekto, obligasyon, asin mga handumon;',
        'Patunay na dai ako basta nawawara sa panahon,',
        'Kundi nakikipaglaban sa sakuyang mga pangitngiton.',
        '',
        'Asin habang ako nagkukwento kan mga pasanon,',
        'Ikaw nagdangog na may dakulang pagdangogon;',
        'An mga sugat na tago sa sakuyang kabubut-on,',
        'Nasasabutan mo maski wara pang pagtaramon.',
        '',
        'Duman naghinay an dating mabagsik na alon,',
        'Asin naglinaw an madiklom na panahon;',
        'Ta minsan palan, an tunay na pagbangon,',
        'Nagtitikang sa pusong may dakulang pagdangogon.',
        '',
        'Kaya kun may maghapot kun sain nagpoon an rason,',
        'Dai sa matam-is na saad o mga tataramon;',
        'Kundi sa barkong nag-abot sa tahaw kan alon,',
        'Asin sa sarong "hello" na nagin sakuyang paglaomon.'
      ],
      translationLines: [
        'Upon the shore of a night steeped in darkness,',
        'A ship arrived by the silent coast;',
        "I stayed beside the harbor's edge,",
        'Not knowing if it brought grace or fresh sorrow.',
        '',
        'So many storms have crossed the sea,',
        'So many promises were buried by forgetting;',
        'So many hearts were worn down by wrongs,',
        'And so many eyes were filled with grief.',
        '',
        'When I heard of what you had once gone through,',
        'I was filled with great hesitation;',
        'For there are people who play with hope',
        'And leave behind marks that cannot be erased.',
        '',
        'So I remained there by the harbor,',
        'Not running toward a new fate;',
        'It seemed better to watch from a distance',
        'Than to fall again into old pain.',
        '',
        'Yet it was not the wind that began the calm,',
        'Nor the waves along the shore;',
        'On that quiet night full of stillness,',
        'It was you who gave the first peace.',
        '',
        'A simple greeting touched with warmth,',
        'Without force, without pride;',
        'Yet in my heart so full of doubt,',
        'It planted a small hope.',
        '',
        'I showed you the work I carry,',
        'My projects, duties, and dreams;',
        'Proof that I am not merely lost in time,',
        'But still fighting through my shadows.',
        '',
        'And while I spoke of all my burdens,',
        'You listened with such deep attention;',
        'The wounds hidden in my spirit,',
        'You understood even before I named them.',
        '',
        'There the once-fierce waves began to soften,',
        'And the darkened weather turned clear;',
        'For sometimes true rising begins',
        'In a heart that knows how to listen.',
        '',
        'So if someone asks where it all began,',
        'It was not with sweet promises or grand words;',
        'But with a ship that reached the waves,',
        'And with one "hello" that became my hope.'
      ]
    },
    {
      id: 2,
      title: 'That One Night We Talked',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Sa gabing tahimik asin may kahiloman,', 'Nag-istoryahan kita na may kaluwasan;'],
      mood: 'Introspective',
      accentColor: '#4F7CAC',
      language: 'bikolano',
      lines: [
        'Sa gabing tahimik asin may kahiloman,',
        'Nag-istoryahan kita na may kaluwasan;',
        'Dai sindaing magpakusog o magpanggaran,',
        'Kundi duwang kaluluwang may kakulangan.',
        '',
        'May gutom sa puso na dai maibitaran,',
        'May handom na piglalaban sa kahiditan;',
        'Nagtaram kita na wara nang pag-iingatan,',
        'Siring baga kita nagkilala na nin kaidtoan.',
        '',
        'An sakuyang pader mataas na hararoman,',
        'Tinukod nin taon nin pagkapirdihan;',
        'Bawat tipak may bakas nin kasakitan,',
        'Asin bawat bato may ngaran na kapalpakan.',
        '',
        'Dakol nang nagtingin sa sakuyang hararoman,',
        'Dakol man an nagsubok nin pagsulod duman;',
        'Pero nagbalik sinda sa parehong kadiklanan,',
        'Na wara man sana nin nabag-o sa sakuyang kamugtakan.',
        '',
        'Pero sa gabing may tahimik na kahadean,',
        'Dai mo ginpusol an pader sa pakikigbaan;',
        'Sarong taram mo sana na may katotoohan,',
        'Asin an hararoman nagkaigwa nin bitakan.',
        '',
        'Habang pigdadangog ko an saimong kaagihan,',
        'Nabati ko an tagong lungkot sa kada tataramon;',
        'May ngisi sa imo pero may kahiditan,',
        'Na tinatago sa likod kan saimong katatawanan.',
        '',
        'Pig-istorya mo an mga suliran sa harong nindoan,',
        'An mga gabing puno nin pag-aalitan;',
        'An mga taram na nagdudulot nin kasakitan,',
        'Asin an paglaom na pirming sinusubukan.',
        '',
        'Asin sa lambang detalye kan saimong istoryahan,',
        'Nabati ko an saimong pagkapagal asin kahinaan;',
        'Dai bilang kapalpakan o kakulangan,',
        'Kundi bilang pusong may dakulang pinasanan.',
        '',
        'Duman ko nasabutan an saimong kalagayan,',
        'Na sa likod kan kusog may nakatagong kalungkutan;',
        'Asin sa likod kan ngisi may pag-uusisa man,',
        'Kun may matitirang tawo na dai magpapabayaan.',
        '',
        'Kaya an gabing yaon dai ko malilipatan,',
        'Ta dai sana kita nagkaigwa nin istoryahan;',
        'Duwang pusong gutom sa pag-intindihan,',
        'An nag-abot asin nagkaigwa nin kahadean.'
      ],
      translationLines: [
        'On a quiet night wrapped in stillness,',
        'We spoke with an easy openness;',
        'Not trying to appear strong or grand,',
        'But as two souls marked by their lacks.',
        '',
        'There was a hunger in the heart that could not be denied,',
        'A dream still struggling through hardship;',
        'We spoke with no more guards between us,',
        'As though we had known each other long ago.',
        '',
        'The wall around me stood high and deep,',
        'Built from years of defeat;',
        'Every piece bore the mark of hurt,',
        'And every stone was named failure.',
        '',
        'Many have looked upon that wall,',
        'Many also tried to enter there;',
        'But they returned to the same distance,',
        'And nothing in my condition changed.',
        '',
        'Yet on that night of quiet calm,',
        'You did not break the wall by force;',
        'One simple truth from your lips,',
        'And a crack appeared in its height.',
        '',
        'As I listened to what you had lived through,',
        'I heard the hidden sadness in every word;',
        'There was a smile in you, yet also strain,',
        'Kept behind your light way of laughing.',
        '',
        'You spoke of the troubles in your home,',
        'Of nights so full of quarrels;',
        'Of words that brought you pain,',
        'And of hope that was constantly tested.',
        '',
        'And in every detail of your story,',
        'I felt your weariness and your weakness;',
        'Not as failure or lack,',
        'But as a heart carrying far too much.',
        '',
        'There I understood your condition,',
        'That behind strength there was hidden sorrow;',
        'And behind the smile there was also a question,',
        'Whether someone would remain and not leave you.',
        '',
        'That is why I cannot forget that night,',
        'For it was not only conversation we were given;',
        'Two hearts hungry to be understood',
        'Met and found a quiet peace.'
      ]
    },
    {
      id: 3,
      title: 'An Tulay sa Kadikloman',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Nag-abot an aldaw nin dakulang pagsubok,', 'An mga pultahan pinasara sa pagdali;'],
      mood: 'Hopeful',
      accentColor: '#6A1B9A',
      language: 'bikolano',
      lines: [
        'Nag-abot an aldaw nin dakulang pagsubok,',
        'An mga pultahan pinasara sa pagdali;',
        'An mga dalan pinutol nin kahiditan,',
        'Asin an paglaom pigsubok sa kahiloman.',
        '',
        'Duwang puso an pinalayo nin kapalaran,',
        'Duwang ngaran an pig-ulang sa kahadean;',
        'An mga taram na dating madaling abuton,',
        'Nagin bihira sa lambang panahon.',
        '',
        'Sa sarong kisapmata nagbago an sitwasyon,',
        'An mga oras nagin puno nin paghulaton;',
        'An dating kasanayan nagin alaala lamang,',
        'Asin an kada minuto may kabug-atan.',
        '',
        'May mga nagsiring na tapos na an lakaw,',
        'Na an barkong naglayag mapapara sa dagat;',
        'Na an bagyo sapat na para magpahingalo,',
        'Asin an kahadean dai na magduro.',
        '',
        'Pero dai ninda aram an katotoohan,',
        'Na may mga pusong dai basta sumusuko;',
        'Na kun sarhan man ninda an sarong dalan,',
        'May matutukod na bago sa kadikloman.',
        '',
        'Habang an iba nagtutukod nin harangon,',
        'May iba man na nagtutukod nin tulayon;',
        'Tahimik sana, wara nin paghambogon,',
        'Pero puno nin kusog asin katuyuhan.',
        '',
        'Sa tahaw kan gabing puno nin kahiditan,',
        'Nagkaigwa nin mga kamot na handang magbulig;',
        'Mga kaibigang nagtindog sa kahadean,',
        'Asin nagtao nin liwanag sa kadikloman.',
        '',
        'May mga mensaheng dai dapat mawara,',
        'May mga pangungusap na dapat maabot pa;',
        'Ta an puso dai man sinusukat nin distansya,',
        'Kundi sa pagpadagos kan saiyang paglaom.',
        '',
        'Asin sa kada tulay na naitukod duman,',
        'May bagong kusog na pigtao kan panahon;',
        'Na bako palan gabos nadadaog nin harangon,',
        'Kun an katuyuan puno nin katotoohan.',
        '',
        'Nahiling ko man an kusog sa saimong puso,',
        'Maski pigpapasan mo an sadiring bagyo;',
        'Maski pigpipilit ka kan mga pagsubok,',
        'Nagpapadagos ka gihapon sa pag-abot.',
        '',
        'Asin sa lambang aldaw nin paghulaton,',
        'Mas lalo kong nasabutan an kahulugan;',
        'Na an tunay na koneksyon sa duwang kaluluwa,',
        'Dai basta napuputol nin simpleng problema.',
        '',
        'Ta may mga butang na lampas sa harangon,',
        'Lampas sa kadikloman asin kalayuan;',
        'Mga bagay na nabubuhay sa paglaom,',
        'Asin nagtitinindog sa tahaw kan panahon.',
        '',
        'Kaya kun may maghapot kun pano ini nabuhay,',
        'Kun pano ini nagduro maski may kadikloman;',
        'Masasabi ko sana sa tahaw kan buhay—',
        'Pigsarad ninda an mga pultahan,',
        'Pero an mga puso nakahanap nin tulayon.'
      ],
      translationLines: [
        'A day of great trial came,',
        'And the doors were shut in haste;',
        'The roads were cut off by hardship,',
        'And hope was tested in the stillness.',
        '',
        'Two hearts were set far apart by fate,',
        'Two names were held apart in silence;',
        'Words once easy to reach',
        'Grew rare with passing days.',
        '',
        'In a blink the whole situation changed,',
        'And the hours became full of waiting;',
        'What once felt familiar became a memory,',
        'And every minute carried weight.',
        '',
        'Some said that the journey was over,',
        'That the ship which sailed would fade at sea;',
        'That the storm was enough to make it rest,',
        'And that the calm would not endure.',
        '',
        'But they did not know the truth,',
        'That some hearts do not surrender easily;',
        'That even if one road is closed,',
        'Another can be built in the dark.',
        '',
        'While some were building barriers,',
        'Others were building bridges;',
        'Quietly, without boasting,',
        'Yet full of strength and purpose.',
        '',
        'On nights filled with hardship,',
        'There were hands willing to help;',
        'Friends who stood alongside the struggle,',
        'And gave light in the darkness.',
        '',
        'There were messages that should not be lost,',
        'And words that still had to arrive;',
        'For the heart is not measured by distance,',
        'But by the way it keeps on hoping.',
        '',
        'And with every bridge built there,',
        'New strength was given by time;',
        'Not everything is defeated by barriers',
        'When purpose is filled with truth.',
        '',
        'I also saw the strength in your heart,',
        'Even while you carried your own storm;',
        'Even when trials pressed upon you,',
        'You still kept moving forward.',
        '',
        'And with every day of waiting,',
        'I understood the meaning more clearly;',
        'That the true bond between two souls',
        'Is not easily broken by simple trouble.',
        '',
        'For there are things beyond all barriers,',
        'Beyond darkness and distance;',
        'Things that live by hope,',
        'And keep standing through time.',
        '',
        'So if someone asks how this survived,',
        'How it endured despite the darkness;',
        'I can only say this of life -',
        'They shut the doors,',
        'But the hearts found a bridge.'
      ]
    },
    {
      id: 4,
      title: 'Kun Magduro an Panahon',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['May siyudad na tinukod sa karagatan,', 'Napapalibutan nin bakal na harangan;'],
      mood: 'Resolute',
      accentColor: '#2C3E50',
      language: 'bikolano',
      lines: [
        'May siyudad na tinukod sa karagatan,',
        'Napapalibutan nin bakal na harangan;',
        'Dakol nang hukbo an nag-abot sa atubangan,',
        'Pero gabos nagbalik sa kadikloman.',
        '',
        'Nagngalitngit an langit sa kahiloman,',
        'Naglinog an daga sa kapatagan;',
        'An mga bandera naglayog sa kalangitan,',
        'Siring tanda nin dakulang gerahan.',
        '',
        'Dakol an pamangkot sa atubangan,',
        'Dakol man an paghusgar sa kahimtangan;',
        'Pig-uukian an lambang katuyuhan,',
        'Asin pigsusukol an katibayan.',
        '',
        'An mga tore nagtindog sa kalayuan,',
        'An mga pader makusog sa katibayan;',
        'Pigbantayan ini nin dating kasakitan,',
        'Asin pinatibay nin pagduduman.',
        '',
        'Dakol nang alon sa karagatan,',
        'Dakol nang bagyo sa kalangitan;',
        'Pero an siyudad nagdanay sa katindugan,',
        'Maski pig-uuran nin kahaditan.',
        '',
        'An mga agi sa tahaw kan kapatagan,',
        'Napuno nin usok asin kadikloman;',
        'Pig-uukian an lambang pundasyon,',
        'Para masukol an tunay na katibayan.',
        '',
        'Asin sa tunga kan maingay na gerahan,',
        'May tahimik na hagad sa kalayuan;',
        'Dai ini kulog kan karagatan,',
        'Kundi hagakgak nin kabubut-an.',
        '',
        'Ta sa likod kan mga katatawanan,',
        'May tagong bakas nin kalungkutan;',
        'Sa likod kan mga simpleng tataramon,',
        'May pusong puno nin pagduduman.',
        '',
        'Nag-abot an tigsik nin panahon,',
        'Siring amihan sa tahaw kan kabubut-on;',
        'May pamangkot na dai lubos na nagtataramon,',
        'Pero mababati sa tahaw kan kahiloman.',
        '',
        'Siring an bulan sa tahaw kan karagatan,',
        'Na pirming natatabunan nin kadikloman;',
        'May kahadlok na magin sarong alaalon,',
        'Na madara sana nin panahon.',
        '',
        'May pantalan sa tahaw kan baybayon,',
        'Na pirming naghuhulat nin pagbalikon;',
        'Dai ini nagdadalagan sa direksyon,',
        'Dai man napapaurag sa panahon.',
        '',
        'An mga parola sa tahaw kan baybayon,',
        'Pirming may sindi sa lambang kahiloman;',
        'Dai ninda gin-aapura an mga layagon,',
        'Kundi piggigiya sinda sa paroroonan.',
        '',
        'Asin sa tunga kan usok kan gerahan,',
        'May tahimik na saad na nabuoan;',
        'Dai bilang kulog sa kalangitan,',
        'Kundi siring bituing may katindugan.',
        '',
        'Ta an tunay na paglaom may katibayan,',
        'Dai basta nalulusaw sa kahaditan;',
        'Maski magngalitngit an kalangitan,',
        'Nagpupundo giraray sa kabubut-an.',
        '',
        'An siyudad nagtinindog sa kadagaan,',
        'An mga pader nakaabot sa katapusan;',
        'Pero may sarong butang na lampas sa husgaran,',
        'Na dai masukol nin ano mang sukolan.',
        '',
        'Kaya sa tahaw kan gabing may kahiloman,',
        'Sa tunga kan bagyo asin gerahan;',
        'May sarong puso na nagpili nin pag-antayan,',
        'Maski magduro pa an panahonan.'
      ],
      translationLines: [
        'There is a city built upon the sea,',
        'Encircled by walls of iron;',
        'Many armies came against it,',
        'Yet all returned to darkness.',
        '',
        'The sky growled in the stillness,',
        'And the earth shook across the plain;',
        'Flags flew high in the heavens,',
        'Like signs of a great war.',
        '',
        'Many questions stood before it,',
        'Many judgments too about its state;',
        'Every purpose was examined,',
        'And every strength was measured.',
        '',
        'Towers stood out in the distance,',
        'Its walls were strong and firm;',
        'Guarded by old pain,',
        'And hardened by hesitation.',
        '',
        'Many waves crossed the sea,',
        'Many storms filled the sky;',
        'Yet the city held its ground,',
        'Even while trouble rained upon it.',
        '',
        'The paths across the plain',
        'Filled with smoke and darkness;',
        'Every foundation was tested',
        'To measure its true strength.',
        '',
        'And in the middle of the noisy war,',
        'There was a quiet invitation from afar;',
        'It was not thunder from the sea,',
        'But the laughter of a soul.',
        '',
        'For behind the laughter,',
        'There were hidden traces of sorrow;',
        'Behind the simplest words,',
        'A heart full of doubt.',
        '',
        'Then the heat of time arrived,',
        'Like a cool wind across the will;',
        'There were questions not fully spoken,',
        'Yet heard within the silence.',
        '',
        'Like the moon above the sea,',
        'Often veiled by darkness;',
        'There was a fear of becoming only a memory,',
        'Carried away by time.',
        '',
        'There is a harbor by the shore,',
        'Always waiting for a return;',
        'It does not run after direction,',
        'Nor is it shaken by time.',
        '',
        'The lighthouses along the shore',
        'Keep their light in every darkness;',
        'They do not hurry the voyagers,',
        'But guide them where they are going.',
        '',
        'And in the smoke of war,',
        'A quiet promise was formed;',
        'Not as thunder in the sky,',
        'But as a star that knew how to stand.',
        '',
        'For true hope has its own firmness,',
        'It does not melt so easily in trouble;',
        'Though the heavens may rage,',
        'It settles once more in the soul.',
        '',
        'The city stood through the battle,',
        'Its walls endured to the end;',
        'Yet there is one thing beyond judgment,',
        'That no measure can contain.',
        '',
        'So on a night full of stillness,',
        'In the midst of storm and war;',
        'There was one heart that chose to wait,',
        'No matter how long time had to endure.'
      ]
    },
    {
      id: 5,
      title: 'The Girl Who Spoke Like Rain',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Some flowers arrive with thunder and flame,', 'Demanding the world to remember their name;'],
      mood: 'Tender',
      accentColor: '#C0829D',
      language: 'english',
      lines: [
        'Some flowers arrive with thunder and flame,',
        'Demanding the world to remember their name;',
        'But you were the hush at the close of the day,',
        'A soft little star that refused to fade away.',
        '',
        'You entered my life without banners unfurled,',
        'Without any wish to astonish the world;',
        'Yet somehow the silence you carried with grace,',
        'Left traces of light in every place.',
        '',
        'The first time I heard your voice through the air,',
        'I forgot every burden and every despair;',
        'It floated so gently through distance and time,',
        'Like a hymn that had wandered from Heaven sublime.',
        '',
        'I listened again, then listened once more,',
        'As though it were waves on a faraway shore;',
        'For every soft syllable fell from above,',
        'Like rain teaching deserts the meaning of love.',
        '',
        'There was sweetness concealed in the way that you spoke,',
        'In the pauses between every word that awoke;',
        'And even your shyness, reluctant to stay,',
        'Made my guarded old heart slowly drift your way.',
        '',
        'For behind every smile there lingered a fear,',
        'A shadow that quietly followed you near;',
        'A wound that reminded your spirit each day,',
        'That not every person is destined to stay.',
        '',
        'I noticed it there in the things left unsaid,',
        'In the caution that walked where your confidence tread;',
        'Yet somehow those fragments made you more real,',
        'A portrait no painter could perfectly reveal.',
        '',
        'You never pretended to shine like the sun,',
        'Or claimed to be flawless before anyone;',
        'Yet the honesty woven through all that you are,',
        'Made you brighter than many who tried to shine far.',
        '',
        'And every small detail I happened to see,',
        'Became unexpectedly precious to me;',
        'The things you called ordinary, simple, or slight,',
        'Somehow transformed into sources of light.',
        '',
        'Your laughter was gentle, your manner was kind,',
        'Leaving echoes that lingered long after in mind;',
        'Like pages revisited time after time,',
        'Still beautiful long after reading each line.',
        '',
        'Then one day you trusted me just enough,',
        'To share little pieces of yourself and your love;',
        'A glimpse through a window carefully drawn,',
        'A portrait illuminated by dawn.',
        '',
        'And when those photographs finally came through,',
        'The world seemed determined to pause for a view;',
        'I saved every image before I could think,',
        'Afraid that a moment might vanish in a blink.',
        '',
        'Not because beauty was all that I saw,',
        'Nor because perfection inspired me with awe;',
        'But because every picture carried your name,',
        'And knowing their owner made them impossible to tame.',
        '',
        'There are sunsets more brilliant than gold in the sky,',
        'And wonders that travelers journey to find;',
        'Yet none of them ever persuaded my heart,',
        'To linger the way you did from the start.',
        '',
        'For beauty alone is a fleeting delight,',
        'A candle that flickers away in the night;',
        'But kindness and softness endure through the years,',
        'Remaining through triumphs and remaining through tears.',
        '',
        'And so when I think of the path that began,',
        'I remember no grand or remarkable plan;',
        'Only a shy little voice reaching over the sea,',
        'And somehow finding its way directly to me.',
        '',
        'If anyone asks what first captured my eyes,',
        'It wasn\'t mere beauty beneath distant skies;',
        'It was a gentle soul learning slowly to trust,',
        'And a quiet young heart that I treasure because it is just... you.'
      ]
    },
    {
      id: 6,
      title: 'At 11:28 PM',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['There are hours that pass like forgotten rain,', 'And hours that vanish without leaving a name;'],
      mood: 'Hopeful',
      accentColor: '#5B7C99',
      language: 'english',
      lines: [
        'There are hours that pass like forgotten rain,',
        'And hours that vanish without leaving a name;',
        'But one quiet moment still lives in my mind,',
        'Like a star that the years will never leave behind.',
        '',
        'The day had been long with its battles and noise,',
        'Filled with responsibilities, burdens, and choice;',
        'Yet somewhere beyond all the things left to do,',
        'My thoughts kept returning to only you.',
        '',
        'Five days had wandered since words took their flight,',
        'Crossing uncertain horizons that night;',
        'And though I stood firm in the promise I\'d made,',
        'I knew some answers cannot simply be weighed.',
        '',
        'For hope is a traveler careful and slow,',
        'A river that chooses its own way to flow;',
        'And hearts that have suffered are often afraid,',
        'To step toward the light after living in shade.',
        '',
        'So I waited in patience, as calm as I could,',
        'Believing that rushing would do no good;',
        'For flowers unfold in their season and time,',
        'Not because someone demands they should climb.',
        '',
        'Then came a moment both simple and small,',
        'No thunder, no trumpet, no grandness at all;',
        'Just a message appearing in quiet delight,',
        'Like dawn finding mountains at the end of the night.',
        '',
        'And somehow the world grew lighter to bear,',
        'As though every burden dissolved into air;',
        'The answer I\'d hoped for, gentle and true,',
        'Arrived carrying pieces of Heaven in view.',
        '',
        'No treasure I\'ve held could compare with that gift,',
        'No victory ever produced such a lift;',
        'For what reached my heart in that silent embrace,',
        'Was something no title or trophy could replace.',
        '',
        'The clock kept its rhythm as always before,',
        'Unaware it had opened a brand-new door;',
        'While somewhere beneath that ordinary sky,',
        'A dream quietly learned it was allowed to fly.',
        '',
        'And so before sleep gently carried me away,',
        'The finest gift found me at the close of the day;',
        'At exactly eleven twenty-eight that night,',
        'You gave one small answer—',
        '',
        'And turned darkness to light.'
      ]
    },
    {
      id: 7,
      title: 'An Langit na Nagbagsak nin Duwang Beses',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Naghinayon pa sana an karagatan,', 'Pagkatapos kan dating kahaditan;'],
      mood: 'Hopeful',
      accentColor: '#E67E22',
      language: 'bikolano',
      lines: [
        'Naghinayon pa sana an karagatan,',
        'Pagkatapos kan dating kahaditan;',
        'Pero nagtipon giraray an kadikloman,',
        'Sa tahaw kan tahimik na kalangitan.',
        '',
        'May bagyong dai nagtaram nin ngaran,',
        'May unos na dai naghatod nin hudyatan;',
        'Basta sana nag-abot sa baybayon,',
        'Asin nagdala nin dakulang kahaditan.',
        '',
        'An mga alon nagkusog sa karagatan,',
        'An mga panganod nagtipon sa kalangitan;',
        'Siring baga an kapalaran mismo,',
        'Nagpili na subukon an kahadean.',
        '',
        'May mga tore na nagkaigwa nin liwanag,',
        'May mga bantay na nagmulat sa kalayuan;',
        'Asin an tahimik na dalan sa kagab-ihon,',
        'Biglang napuno nin pag-aalangan.',
        '',
        'Naglinog an puso sa kahiloman,',
        'Siring dahon na ginuyod kan habagat;',
        'Ta may kahadlok na an sarong paglaoman,',
        'Mahadit sa tunga kan kadikloman.',
        '',
        'Kaya nagtukod giraray nin tulayan,',
        'Sa tahaw kan dagat asin kalayuan;',
        'Dai para sa giringgitan o kadagaan,',
        'Kundi para sa pagpadagos kan kahadean.',
        '',
        'May mga dalan na nakalihim sa kagabsan,',
        'May mga parola sa tahaw kan baybayon;',
        'Asin maski nagngalitngit an kalangitan,',
        'Nagdanay pa giraray an katuyuhan.',
        '',
        'Ta an tunay na paglaom dai maruruba,',
        'Maski pig-uuran nin dakulang bagyo;',
        'Dai ini basta nalulunod sa alon,',
        'Kun may pusong pirming nag-aantabayon.',
        '',
        'Asin sa tunga kan usok kan gerahan,',
        'May sarong kamot na dai bumitawan;',
        'Maski nag-uuran nin kahaditan,',
        'Dai nagluya an saiyang katindugan.',
        '',
        'Nag-abot an gabi na may kahiloman,',
        'Puno nin pangutana asin pagduduman;',
        'Pero sa laog kan tahimik na kabubut-on,',
        'May sinding dai mahayup sa panahon.',
        '',
        'Siring an buwan sa tahaw kan karagatan,',
        'Na pirming nagbabalik sa kadikloman;',
        'Maski matabunan nin mga panganod,',
        'Dai nawawara an saiyang kahadeanon.',
        '',
        'May mga tulay na dai nakikita nin mata,',
        'May mga dalan na dai nahihiling nin iba;',
        'Pero an mga ini nagtitinindog,',
        'Sa tahaw kan dakulang paglaomon.',
        '',
        'Asin may sarong payak na handumanon,',
        'Na pinanday sa tunga kan kahiloman;',
        'Dai sa bakal, dai sa bato man,',
        'Kundi sa pag-antay asin kabubut-on.',
        '',
        'Ta may mga bagyo na dai tinatabangan,',
        'Nin kusog o mataras na armasan;',
        'Kundi nin pusong dai nagdadalagan,',
        'Maski pig-uuran nin kahaditan.',
        '',
        'An langit nagbagsak nin duwang beses,',
        'Sa tahaw kan satong kinabubuhian;',
        'Pero an mga bituin dai nagkararaot,',
        'Sa tahaw kan satong kahadeanon.',
        '',
        'Asin pagluwas kan bagyo sa kalangitan,',
        'Nagdanay pa giraray an katindugan;',
        'Ta an mga bagay na may kahulugan,',
        'Dai basta natatapos sa kahaditan.',
        '',
        'Kaya kun may aldaw na dai malilipatan,',
        'Iyo an gabing puno nin kadikloman;',
        'Ta maski nagbagsak an langit nin duwang beses,',
        'Nag-abot kita sa parehas na kahadeanon.'
      ],
      translationLines: [
        'The sea had only just begun to quiet',
        'After the former trouble;',
        'Yet darkness gathered once again',
        'Across the silent sky.',
        '',
        'There was a storm that named itself to no one,',
        'A tempest that sent no warning;',
        'It simply came upon the shore',
        'And carried great trouble with it.',
        '',
        'The waves grew fierce upon the sea,',
        'Clouds gathered in the sky;',
        'As though fate itself',
        'Had chosen to test the peace.',
        '',
        'Towers lit up in the distance,',
        'Watchers woke from afar;',
        'And the quiet road of night',
        'Suddenly filled with unease.',
        '',
        'The heart trembled in the dark,',
        'Like a leaf dragged by the monsoon;',
        'For there was fear that a single hope',
        'Might break within the darkness.',
        '',
        'So a bridge was built again,',
        'Across the sea and the distance;',
        'Not for shouting or triumph,',
        'But so peace could go on.',
        '',
        'There were roads hidden at dawn,',
        'There were lighthouses by the shore;',
        'And even while the sky raged,',
        'Purpose remained.',
        '',
        'True hope does not collapse easily,',
        'Even beneath the weight of storms;',
        'It does not simply drown in the waves,',
        'When a heart keeps waiting.',
        '',
        'And in the smoke of battle,',
        'There was one hand that did not let go;',
        'Though hardship rained down,',
        'Its resolve did not grow weak.',
        '',
        'Night came wrapped in stillness,',
        'Full of questions and doubt;',
        'Yet within the quiet soul',
        'A flame remained that time could not put out.',
        '',
        'Like the moon above the sea,',
        'Always returning through the dark;',
        'Though the clouds may cover it,',
        'Its calm is not erased.',
        '',
        'There are bridges no eye can see,',
        'Roads others do not notice;',
        'Yet these remain standing',
        'On top of great hope.',
        '',
        'And there was one simple remembrance,',
        'Forged in the middle of the silence;',
        'Not of steel, nor of stone,',
        'But of waiting and of will.',
        '',
        'For some storms are not endured',
        'By strength or sharpened arms;',
        'But by a heart that does not flee',
        'Even when trouble falls like rain.',
        '',
        'The sky fell twice',
        'Over our lives;',
        'Yet the stars were not destroyed',
        'Above our quiet peace.',
        '',
        'And when the storm left the heavens,',
        'Resolve was still there;',
        'For things that truly matter',
        'Do not end because of hardship.',
        '',
        'So if there is a day I cannot forget,',
        'It is that night full of darkness;',
        'For even when the sky fell twice,',
        'We still arrived at the same peace.'
      ]
    },
    {
      id: 8,
      title: 'An Rason na Dai Nauubos',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Kun haputon ako kun nano an rason,', 'Nano an pinaghalinan kan kahadeanon;'],
      mood: 'Introspective',
      accentColor: '#A0835C',
      language: 'bikolano',
      lines: [
        'Kun haputon ako kun nano an rason,',
        'Nano an pinaghalinan kan kahadeanon;',
        'Dai ako mataram nin sarong bagay lamang,',
        'Ta dakol siyang bitbit na kahulugan.',
        '',
        'Dai siya nag-abot siring kusog na bagyo,',
        'Dai man siring kulog sa kalangitan;',
        'Nag-abot siya siring hinay na alon,',
        'Na marahay sanang naghahaplos sa baybayon.',
        '',
        'May mga tawo na naghihiling nin kusog,',
        'May mga tawo na naghihiling nin dangal;',
        'Pero may kagayunan sa kalambingan,',
        'Na dai masusukol nin ano mang sukatan.',
        '',
        'An saiyang mga tataramon na mahinay,',
        'Siring habagat sa tahaw kan kagabsan;',
        'Dai nag-uutob nin dakulang giringgitan,',
        'Pero nakakahiling nin kapayapaan.',
        '',
        'Asin sa lambang aldaw na nag-aagi,',
        'Mas lalo kong nasasabutan an katotoohan;',
        'Na an pinakamalumoy na mga puso,',
        'An pirming may pinakadakulang kahulugan.',
        '',
        'An primerong beses na narungog ko siya,',
        'Siring naghinayon an bilog na kinaban;',
        'An mga alon nagdanay sa karagatan,',
        'Asin naghilom an lambang kaguluhan.',
        '',
        'An saiyang boses dai sana sarong awit,',
        'Dai man sana sarong ordinaryong tataramon;',
        'Siring ini harong sa tahaw kan bagyo,',
        'Na pirming may sinding paglaomon.',
        '',
        'Asin sa lambang pulong na naglalakaw,',
        'May kalambingan na dai matutumbasan;',
        'Siring bulan na naghahaplos sa dagat,',
        'Sa tahaw kan tahimik na kagabsan.',
        '',
        'Dakol na awit an pigdangog kan talinga,',
        'Dakol nang himig an nag-agi sa panahon;',
        'Pero may mga boses na nag-iiwan,',
        'Nin permanente nang handumanon.',
        '',
        'Iyo an klase nin liwanag na dai masilaw,',
        'Dai siring adlaw na makusog an sindi;',
        'Kundi siring bituing tahimik sa langit,',
        'Na pirming presente sa kagab-ihon.',
        '',
        'Sa primerong paghiling, siya mahihiyaon,',
        'Siring bulaklak sa tahaw kan kagabsan;',
        'Pero an mga bulaklak na mahihiyaon,',
        'An pirming may pinakamarahay na kahumotan.',
        '',
        'Sa likod kan mahinay niyang pagngisi,',
        'May kasaysayan nin dakulang pakigbato;',
        'Mga bagyong nag-agi sa saiyang dagat,',
        'Asin mga unos na dai niya pinili.',
        '',
        'May mga sugat na dai nakikita nin mata,',
        'May mga kahadlok na dai pirming natataram;',
        'Pero nagpadagos siya sa paglakaw,',
        'Maski mabug-at an pinapasan.',
        '',
        'An kusog dai pirming maingay,',
        'Dai pirming may espada o bandila;',
        'Kun minsan ini sarong pusong pagod,',
        'Na nagpapadagos maski may luha.',
        '',
        'Asin iyo an kusog na nahiling ko saiya,',
        'Dai an kusog kan giringgitan o kadagaan;',
        'Kundi an kusog kan sarong kaluluwa,',
        'Na nagpupundo maski sa kahaditan.',
        '',
        'May mga kuta na tinukod nin panahon,',
        'Mga pader na pinatibay nin kasakitan;',
        'Asin may mga pultahan na dai basta,',
        'Nagbubukas sa lambang nag-aabotan.',
        '',
        'Pero hinay-hinay nagbukas an pultahan,',
        'Dai sa kusog o pagpilit man;',
        'Kundi sa tahaw kan padagos na panahon,',
        'Asin sa simpleng katotoohan.',
        '',
        'An pagtiwala siring tanom sa umahan,',
        'Dai nag-uusbong sa sarong kagab-ihon;',
        'Pig-aalagaan ini nin pag-antay,',
        'Asin nin malinig na katuyuhan.',
        '',
        'Asin sa lambang istoryang ibinahagi,',
        'Sa lambang kahadlok na ipinahiling;',
        'Mas lalo kong nasabutan an karangalan,',
        'Kan pagtiwalang ipinagkaloob sa sakuya.',
        '',
        'Ta an pinakamarahay na mga regalo,',
        'Dai nakukuyog sa kahon o laso;',
        'Kun minsan ini an simpleng pagtiwala,',
        'Kan sarong pusong dakol nang pinag-agihan.',
        '',
        'May mga tawo na nag-aagi sana,',
        'Siring alon na nag-iiwan nin bakas;',
        'Pero may mga tawo man na nagbabago,',
        'Kan direksyon kan satong dagat.',
        '',
        'Bago siya, dakol an tahimik na kagab-ihon,',
        'Dakol an mga adlawan na wara nin kulay;',
        'Pero may mga tawo talagang nag-aabot,',
        'Na may dalang bagong pagsirang.',
        '',
        'Dai niya aram an gabos niyang epekto,',
        'Sa tahaw kan sakuyang kabubut-on;',
        'Kung pano an sarong simpleng mensahe,',
        'Nakakapadanay kan kaguluhan.',
        '',
        'Asin sa tahaw kan lambang pagsubok,',
        'May rason na para magpadagos;',
        'Dai ta pirming madali an dalan,',
        'Pero mas marahay an paglakaw.',
        '',
        'Ta may mga paglaom na mas nagkakusog,',
        'Kun may sarong tawo na kaiba;',
        'Siring barkong mas kampante maglayag,',
        'Kun may nakikitang parola.',
        '',
        'Kaya kun haputon ako kun nano an rason,',
        'Dai sapat an sabat na "ta magayon siya";',
        'Ta dakol pang bulan sa kalangitan,',
        'Asin dakol pang bulaklak sa kadlagan.',
        '',
        'Dai man sapat an sabat na "ta malumoy siya,"',
        'Maski katotoohan man iyan;',
        'Ta an rason dai nakukulong,',
        'Sa sarong linya nin tataramon.',
        '',
        'An rason iyo an bug-os niyang pagkatawo,',
        'An saiyang ngisi asin kalungkutan;',
        'An saiyang kusog asin kahinaan,',
        'Asin an saiyang bug-os na katawuhan.',
        '',
        'An rason iyo an paagi niyang magpadagos,',
        'Maski pig-uuran nin kahaditan;',
        'An paagi niyang magliwanag,',
        'Maski napapalibutan nin kadikloman.',
        '',
        'Kaya kun may sarong katotoohan lamang,',
        'Na gusto kong dal-on sa lambang panahon;',
        'Iyo ini: dai ako nahulog sa sarong detalye—',
        'Nahulog ako sa bug-os niyang pagkatawo.'
      ],
      translationLines: [
        'If you ask me what the reason is,',
        'What gave rise to this quiet peace;',
        'I cannot answer with only one thing,',
        'For it carries so much meaning.',
        '',
        'She did not arrive like a violent storm,',
        'Nor like thunder in the sky;',
        'She came like a gentle wave,',
        'Softly touching the shore.',
        '',
        'Some people look for strength,',
        'Some people look for prestige;',
        'But there is a beauty in tenderness',
        'That no measure can fully weigh.',
        '',
        'Her words, spoken softly,',
        'Are like a breeze at dawn;',
        'They do not bring loud clamor,',
        'Yet they somehow bring peace.',
        '',
        'And with each passing day,',
        'I understand the truth more clearly;',
        'That the gentlest hearts',
        'Often hold the deepest meaning.',
        '',
        'The first time I heard her,',
        'It was as if the whole world grew quiet;',
        'The waves rested on the sea,',
        'And every unrest fell silent.',
        '',
        'Her voice is not merely a song,',
        'Nor just an ordinary way of speaking;',
        'It is like a home in the middle of a storm,',
        'Always lit with hope.',
        '',
        'And in every word that moves,',
        'There is a tenderness without equal;',
        'Like the moon brushing the sea',
        'In the hush of dawn.',
        '',
        'The ears have heard many songs,',
        'Many melodies have passed through time;',
        'But there are voices that leave behind',
        'A memory that stays.',
        '',
        'It is the kind of light that does not blind,',
        'Not like the sun at its brightest;',
        'But like a quiet star in the sky,',
        'Always present through the night.',
        '',
        'At first glance she seems shy,',
        'Like a flower at daybreak;',
        'Yet the shy flowers',
        'Often carry the finest fragrance.',
        '',
        'Behind her gentle smile,',
        'There is a history of hard battles;',
        'Storms that crossed her sea,',
        'And tempests she never chose.',
        '',
        'There are wounds unseen by the eye,',
        'And fears not always spoken;',
        'Yet she kept on walking',
        'Even under a heavy weight.',
        '',
        'Strength is not always loud,',
        'Not always bearing swords or flags;',
        'Sometimes it is a tired heart',
        'That keeps going even with tears.',
        '',
        'And that is the strength I saw in her,',
        'Not the strength of shouting or victory;',
        'But the strength of a soul',
        'That remains steady even in hardship.',
        '',
        'There are fortresses built by time,',
        'Walls strengthened by pain;',
        'And there are doors that do not easily',
        'Open to everyone who arrives.',
        '',
        'Yet little by little the door opened,',
        'Not through force or pressure;',
        'But through steady time',
        'And simple honesty.',
        '',
        'Trust is like a plant in a field,',
        'It does not bloom in one night;',
        'It is tended by patience',
        'And by clear intention.',
        '',
        'And in every story she shared,',
        'In every fear she revealed;',
        'I understood more fully the honor',
        'Of the trust she gave to me.',
        '',
        'For the finest gifts',
        'Do not come wrapped in boxes or ribbon;',
        'Sometimes they are the simple trust',
        'Of a heart that has gone through much.',
        '',
        'Some people only pass through,',
        'Like waves that leave traces;',
        'But some people change',
        'The course of our sea.',
        '',
        'Before her, there were many quiet nights,',
        'And many colorless days;',
        'But some people truly arrive',
        'Carrying a new sunrise.',
        '',
        'She does not know the full effect she has',
        'Within my own heart;',
        'How one simple message from her',
        'Can settle the unrest.',
        '',
        'And in the midst of every trial,',
        'There is a reason to keep going;',
        'The road is not always easy,',
        'But the walking becomes better.',
        '',
        'Some hopes grow stronger',
        'When there is someone beside them;',
        'Like a ship that sails more calmly',
        'When it can see a lighthouse.',
        '',
        'So if you ask me what the reason is,',
        '"It is because she is beautiful" is not enough;',
        'There are many moons in the sky,',
        'And many flowers in the field.',
        '',
        '"It is because she is gentle" is not enough either,',
        'Though that is also true;',
        'For the reason cannot be contained',
        'In a single line of words.',
        '',
        'The reason is her whole self,',
        'Her smile and her sadness;',
        'Her strength and her weakness,',
        'And her full humanity.',
        '',
        'The reason is the way she keeps going,',
        'Even while trouble rains on her;',
        'The way she still gives light,',
        'Even when surrounded by darkness.',
        '',
        'So if there is one truth',
        'I wish to carry through all seasons,',
        'It is this: I did not fall for one detail -',
        'I fell for all that she is.'
      ]
    },
    {
      id: 9,
      title: 'An Pamula kan Pusong Dai Nasanay',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Dai ko aram kun taano ako namumula sa kahiloman,', 'Kun taano nagrurugpa an puso sa simpleng tataramon;'],
      mood: 'Tender',
      accentColor: '#6C3483',
      language: 'bikolano',
      lines: [
        'Dai ko aram kun taano ako namumula sa kahiloman,',
        'Kun taano nagrurugpa an puso sa simpleng tataramon;',
        'Baga may bulan na nagtutukar sa sakuyang kabubut-on,',
        'Asin may liwanag na nagbababa sa sakuyang panahon.',
        '',
        'Dai man ini dahil sa kagayunan lamang sa atubangan,',
        'Dai man dahil sa ngisi na siring bulaklak sa kadlagan;',
        'Kundi dahil sa pag-abot nin sarong kahadean,',
        'Na dai ko pa lubos namidbidan sa dating kaagihan.',
        '',
        'Ta may mga bagay na sadit sa ibang pagmamasdan,',
        'Pero sa pusong napagal, nagigin dakulang kahulugan;',
        'Sarong “kumain ka na?” sa tunga kan aldawan,',
        'Nagin kandila sa dating malamig na kahiloman.',
        '',
        'Sarong “magpahinga ka” na may tunay na pag-aram,',
        'Dai sana tataramon na nag-agi sa talinga;',
        'Kundi siring habagat na humaplos sa kaluluwa,',
        'Asin nagturo na may nag-aalala pa sa sakuya.',
        '',
        'Kun minsan an puso dai namumula sa pagharana,',
        'Kundi sa pag-abot nin pag-ataman na tama;',
        'Ta an bagay na dapat normal sa kinaban,',
        'Sa napabayaan na puso, nagigin katingalahan.',
        '',
        'Dai ko sanang inisip na an simpleng paglingap,',
        'Makakapagpaalon sa tahimik kong dagat;',
        'Pero kan ika nag-abot na may pag-iingat,',
        'An dating pader nagkaigwa nin bitak.',
        '',
        'An mga mata ko nasanay sa paglikay,',
        'An puso ko nasanay sa pag-antabay;',
        'Pero kan ika nagtaram nin marahay na pagdamay,',
        'Nagkamoot an aldaw sa dating pagkawaray.',
        '',
        'Dai ako namula dahil ako napildi sa kahadean,',
        'Namula ako dahil ako nahilingan nin kahalagahan;',
        'Sa kalibutan na pirming nangayo nin kalakasan,',
        'Ikaw an nagpaheling na puwede man an kalambingan.',
        '',
        'May mga taong nag-aagi siring bagyong maluya,',
        'May mga taong nag-iiwan nin sugat sa kaluluwa;',
        'Pero ika, sa tahimik mong paagi asin pag-unawa,',
        'Nag-abot siring uran na nakakapahuway sa daga.',
        '',
        'Kun haputon ninda kun taano ako napapahiyom,',
        'Dai ko masabi sa sarong sadit na pagtaramon;',
        'Ta sa lambang paglingap mo sa sakuyang kabubut-on,',
        'May hinay na bulaklak na nagbubukas sa panahon.',
        '',
        'Nasanay ako sa laban, sa bagsik, sa gerahan,',
        'Sa pagpasan nin mundo sa sakuyang abagan;',
        'Pero ika, dai mo ako ginpirit sa kadakulan,',
        'Ginpahiling mo na puwede akong mahumanay sa kahiloman.',
        '',
        'Ika an nagpaheling na dai dapat pirming matibay,',
        'Na an pagod na puso puwede man magpahuway;',
        'Na an tawo maski dakol an kaya sa buhay,',
        'Nagkakaipo man nin kamot na mag-aakay.',
        '',
        'Kun nag-aalala ka sa sakuyang pagpahinga,',
        'May init na naglalakaw sa sakuyang hininga;',
        'Ta sa simple mong pag-ataman asin pag-aruga,',
        'Nahihiling ko an bagay na haloy kong hinahanap.',
        '',
        'Kun nagagalit ka dahil dai ako nagtuturog,',
        'Dai ko nababati an galit, kundi pag-irog;',
        'Ta minsan an sermon na may kabug-at,',
        'Iyo palan an paglingap na may pag-angat.',
        '',
        'Kun sinasabi mong dapat ako mag-ingat sa lawas,',
        'Naduduman ako sa tahimik kong pagluwas;',
        'Ta may nagbabantay na sa sakuyang paghinga,',
        'Na dai ako ginagibo sanang kasangkapan.',
        '',
        'Dai ko aram kun pano ipapaliwanag an pamula,',
        'Kun pano an simpleng pag-alala nagigin musika;',
        'Pero sa lambang sandali na ika may pag-aruga,',
        'An puso kong napagal, nahihiling an pag-asa.',
        '',
        'Dai ko sanay na ako an pipilion sa kadakulan,',
        'Dai ko sanay na ako an aalagaan sa kahiloman;',
        'Kaya kun ika nag-aabot nin malinaw na kahadean,',
        'An sakuyang mukha nagigin pula sa katingalahan.',
        '',
        'Ta haloy akong naglakaw sa mga dalan nin pagduduman,',
        'Nagdadara nin mga sugat asin kalungkutan;',
        'Pero ika nag-abot na may malinig na katuyuhan,',
        'Asin dai ko aram kun pano tatanggapon an kabutihan.',
        '',
        'An puso na haloy nang nasanay sa pagpabaya,',
        'Nalilito kun inaataman na nin tama;',
        'Kaya kun ika nagiging malumoy sa sakuya,',
        'Namumula ako dahil bago an ginhawa.',
        '',
        'Dai ini pamula nin harot o kapusukan,',
        'Kundi pamula nin pusong nakahiling nin katotoohan;',
        'Na may tawo palang makakasabot sa kahinaan,',
        'Asin dai magagamit ini bilang sandatahan.',
        '',
        'Kun ako nagsasabi nin takot sa panahon,',
        'Ika dai nagtatawa sa sakuyang kabubut-on;',
        'Pigdadangog mo an mga luha kan kahiloman,',
        'Asin ginbabalot mo ini nin pag-intindihan.',
        '',
        'Kun ako napapagod sa dakulang gerahan,',
        'Ika nagigin harong sa tunga kan kalangitan;',
        'Dai mo ginpapara an sakuyang katindugan,',
        'Pero tinuturuan mo akong huminga sa kahiloman.',
        '',
        'Duman ako namumula sa tahaw kan pagduman,',
        'Ta dai ko akalaing may ganitong kahulugan;',
        'An pag-ibig palan bako sana pag-angkon,',
        'Kundi paglingap sa lambang sugat kan kabubut-on.',
        '',
        'Ika dai nag-abot para akong gamiton,',
        'Dai man para sa sugat ko magtukod nin kahadeanon;',
        'Nag-abot ka siring tawo na may paglaomon,',
        'Na handang makidangog sa sakuyang kahiloman.',
        '',
        'Kun ika nagiging mahiyain sa atubangan,',
        'Mas lalo kong nahihiling an saimong kagayunan;',
        'Ta sa lambang hiya asin mahinay na katatawanan,',
        'May bulaklak na nagtatago sa kadlagan.',
        '',
        'Kun an boses mo nag-aagi sa talinga,',
        'Baga ulap na nagdadara nin ginhawa;',
        'Dai ko napapansin na ako palan nakangisi,',
        'Ta an puso ko nakasakay sa ulap.',
        '',
        'Narurungog ko an lambing sa lambang pagtaramon,',
        'Narurungog ko man an takot sa likod kan kahiloman;',
        'Kaya imbes na lumayo sa saimong pagduduman,',
        'Mas lalo kong gustong magdanay sa harongon.',
        '',
        'Ta an saimong kahinaan dai nagpapababa sa kahalagahan,',
        'Dai man nagpapasira kan saimong katawuhan;',
        'Kun bako pa ngani, mas pinapahiling an katotoohan,',
        'Na ika tawo, mahal, asin dapat pahalagahan.',
        '',
        'Duman ako namumula, sa simpleng pagkakilala,',
        'Sa paagi mong dai nagtatago kan kaluluwa;',
        'Ta may kagayunan na dai makukua sa larawan,',
        'Kundi sa pusong naglalakaw na may katotoohan.',
        '',
        'Kun nagpadara ka nin mga larawan,',
        'Dai ko napigilan an sakuyang katingalahan;',
        'Dai dahil sa mata lamang o sa ngaran,',
        'Kundi dahil ikaw an nasa lambang larawan.',
        '',
        'Ginsave ko an mga ini sa sakuyang handumanan,',
        'Siring mga bituin sa madiklom na kalangitan;',
        'Ta kun an mundo magin mabug-at sa kahimtangan,',
        'May maheling akong rason para sa paglaoman.',
        '',
        'Pero maski dai ko maheling an saimong dagway,',
        'An saimong kabutihan nagpapadanay sa buhay;',
        'Ta an tunay na pagkagusto dai sana sa pagmasid,',
        'Kundi sa puso na dai gusto magsakit.',
        '',
        'Kun ika nag-aalala kun ako ba mapagal,',
        'An dating sugat ko nagiging mas magaan;',
        'Ta an simpleng pagtanong na may kalambingan,',
        'Nagpapahiling na ako may kahalagahan.',
        '',
        'Dai ko dapat ika ikumpara sa mga kaagihan,',
        'Pero dai ko man maitatanggi an kaibahan;',
        'Ta kun an iba nagpaheling nin kasakitan,',
        'Ika nagpaheling nin marahay na kahadean.',
        '',
        'Kun kaya ako namumula sa saimong pag-ataman,',
        'Dahil ini an dati kong haloy na ginhahanap;',
        'Dai para pagsilbihan ako sa kapalaluan,',
        'Kundi para maramdaman na ako dai pinababayaan.',
        '',
        'Ika an paalala na an gugma may kalinigan,',
        'Na an pag-ibig dai dapat puno nin kahaditan;',
        'Na puwede palang mahalin nin may paggalang,',
        'Asin pahalagahan maski sa kahinaan.',
        '',
        'Dai mo ako ginpakusog sa pilitan,',
        'Dai mo ako ginpaurag sa pagdadalagan;',
        'Hinay-hinay mo akong ginpatindog sa kahiloman,',
        'Siring kandilang binantayan sa kadikloman.',
        '',
        'Kun sinasabi mong “ako iyo” sa kahadean,',
        'An puso ko nagriribok sa kahiloman;',
        'Ta bako ini pag-angkon na may kadena,',
        'Kundi pagpili na may katotoohan.',
        '',
        'Kun ika nagigin malambing sa pagtaramon,',
        'Dai ko aram kun sain ibubutang an kabubut-on;',
        'Baga nagiging bata an pusong dating matibay,',
        'Ta sa wakas may nag-aabot nin pagdamay.',
        '',
        'An pamula ko bako dahil ako marupok,',
        'Kundi dahil an dating lamig ko nawawara;',
        'Siring yelong natutunaw sa kaadawan,',
        'Pag nag-abot an init nin kalambingan.',
        '',
        'Dai ko sanay na may maghihintay sa sakuya,',
        'Dai ko sanay na may mangangamusta sa sakuya;',
        'Kaya kun ika naghahanap kan sakuyang presensya,',
        'Namumula ako sa tahimik na tuwa.',
        '',
        'Dai ko sanay na may magtatanggol sa kahadean,',
        'Dai ko sanay na may tatanggap sa kapagalan;',
        'Kaya kun ika nagigin harong sa kagab-ihon,',
        'An sakuyang puso nagpapasalamat sa panahon.',
        '',
        'Ta an pinakamabigat na parte kan kaagihan,',
        'Bako sana sugat kundi an pag-iisahan;',
        'Pero ika nag-abot na may pagdamay,',
        'Asin tinuruan mo akong dai na mag-isahan.',
        '',
        'Kun minsan dai ko masabi an sakuyang pagkapula,',
        'Ta nahihiya man ako sa sadiring kaluluwa;',
        'Pero an katotoohan, ika an dahilan,',
        'Kun taano an puso ko nagkakaigwa nin kapayapaan.',
        '',
        'Dai ako sanay na ako an mamahalon nin tama,',
        'Dai ako sanay na ako an pipilion nin maingat;',
        'Kaya kun ika nagpapaheling nin kabutihan,',
        'An puso ko nauubusan nin panangga.',
        '',
        'Sa lambang “ingat” mo may liwanag,',
        'Sa lambang “tulog na” may paglingap;',
        'Sa lambang “kumain ka” may kahulugan,',
        'Sa lambang “nandito ako” may katibayan.',
        '',
        'Dai ko pigmamaliit an mga sadit na bagay,',
        'Ta iyan an bumubuhay sa pagod na buhay;',
        'An mga simpleng tataramon na may pagdamay,',
        'Mas makusog pa kaysa dakulang harana.',
        '',
        'Kun ako namumula, iyo an sakuyang pagsabot,',
        'Na an gugma dai pirming maingay an pag-abot;',
        'Kun minsan ini mahinay na pag-ataman,',
        'Na dai nagtataram pero puno nin kahulugan.',
        '',
        'Ika an unang nagpaheling kan pagtrato,',
        'Na dai nakakasugat, dai nakakalunod;',
        'Pagtrato na may respeto asin pag-iingat,',
        'Na sa dating buhay ko haloy kong hinahanap.',
        '',
        'Kaya kun an mukha ko namumula sa kahiloman,',
        'Dai ini kababawan o simpleng kilig lamang;',
        'Ini an pusong nakasabot sa katotoohan,',
        'Na sa wakas, may nagmahal nang may paggalang.',
        '',
        'Asin kun may maghapot kun taano ako namumula,',
        'Sasabihon ko sa tahaw kan sakuyang kaluluwa;',
        'Ta sa lambang pagtrato mong marahay sa sakuya,',
        'Nabubuhay an parte kong dati nang nawara.',
        '',
        'Kaya an pamula ko bako sana kulay,',
        'Kundi handog kan pusong nakaabot sa buhay;',
        'Ta kan tinrato mo akong tama sa kahiloman,',
        'An buong pagkatao ko natutong mamula sa kahadean.'
      ],
      translationLines: [
        'I do not know why I blush in the quiet,',
        'Why my heart trembles at simple words;',
        'As if a moon were playing inside my spirit,',
        'And a light were falling over my days.',
        '',
        'It is not only because of beauty before me,',
        'Nor because of a smile like flowers in bloom;',
        'But because a kind of peace arrived',
        'I had not fully known in what came before.',
        '',
        'There are things that seem small to other eyes,',
        'Yet to a weary heart they mean so much;',
        'A simple "Have you eaten?" in the middle of the day',
        'Became a candle in what used to be a cold night.',
        '',
        'A simple "Get some rest" said with real concern,',
        'Not just words passing by the ear;',
        'But like a breeze brushing the soul,',
        'Teaching me that someone still worries for me.',
        '',
        'Sometimes the heart does not blush because of serenades,',
        'But because care arrives in the right way;',
        'What should have been ordinary in this world',
        'Becomes a wonder to a neglected heart.',
        '',
        'I never thought that simple tenderness',
        'Could stir waves in my quiet sea;',
        'But when you came with gentleness,',
        'The old wall began to crack.',
        '',
        'My eyes had grown used to looking away,',
        'My heart had grown used to waiting;',
        'But when you spoke with gentle comfort,',
        'Daylight reached what had once been empty.',
        '',
        'I did not blush because I lost some battle,',
        'I blushed because I was shown my worth;',
        'In a world that always demanded strength,',
        'You showed me that tenderness can also exist.',
        '',
        'Some people pass like a harsh storm,',
        'Some people leave wounds in the soul;',
        'But you, through your quiet way and understanding,',
        'Came like rain that lets the earth rest.',
        '',
        'If they ask why I keep smiling,',
        'I cannot answer in a few small words;',
        'For with every care you show my heart,',
        'A quiet flower opens in time.',
        '',
        'I grew used to struggle, to harshness, to war,',
        'To carrying a whole world on my shoulders;',
        'But you did not force me into greatness,',
        'You showed me I could become gentle in the quiet.',
        '',
        'You showed me that I need not always be strong,',
        'That a tired heart is allowed to rest;',
        'That a person, no matter how much he can bear,',
        'May still need a hand to guide him.',
        '',
        'When you worry over whether I have rested,',
        'A warmth moves through my breath;',
        'For in your simple care and sheltering way,',
        'I see the thing I long looked for.',
        '',
        'When you scold me for not sleeping,',
        'I do not hear anger, but affection;',
        'For sometimes a heavy little sermon',
        'Is really care trying to lift me up.',
        '',
        'When you tell me I should take care of my body,',
        'I pause in quiet thought;',
        'For someone is now watching over my breathing,',
        'And not treating me as a mere tool.',
        '',
        'I do not know how to explain this blush,',
        'How simple concern becomes music;',
        'But in every moment you show tenderness,',
        'My weary heart sees hope.',
        '',
        'I am not used to being the one chosen,',
        'Not used to being cared for in the quiet;',
        'So when you offer a clear and gentle peace,',
        'My face turns red in wonder.',
        '',
        'For I have long walked roads of doubt,',
        'Carrying wounds and sadness;',
        'But you arrived with clean intention,',
        'And I do not know how to receive such goodness.',
        '',
        'A heart long used to neglect',
        'Grows confused when it is finally cared for well;',
        'So when you become gentle with me,',
        'I blush because the feeling is new.',
        '',
        'This is not the blush of playfulness or haste,',
        'But the blush of a heart that has seen the truth;',
        'That someone can understand weakness',
        'And not use it as a weapon.',
        '',
        'When I speak of my fears about what lies ahead,',
        'You do not laugh at my heart;',
        'You listen to tears born in the dark,',
        'And wrap them in understanding.',
        '',
        'When I grow tired from a great battle,',
        'You become a home beneath the sky;',
        'You do not put out my strength,',
        'But teach me how to breathe again in the quiet.',
        '',
        'That is where my blushing comes from,',
        'For I never thought it could mean this much;',
        'Love, it seems, is not merely possession,',
        'But tending every wound of the soul.',
        '',
        'You did not come to use me,',
        'Nor to build your peace from my wounds;',
        'You came like a person full of hope,',
        'Willing to listen to my silence.',
        '',
        'When you grow shy before me,',
        'I see your beauty even more clearly;',
        'For in every blush and soft laugh,',
        'A flower hides in the field.',
        '',
        'When your voice reaches my ear,',
        'It feels like a cloud carrying relief;',
        'I do not notice that I am already smiling,',
        'Because my heart has climbed into the sky.',
        '',
        'I hear affection in every word,',
        'And fear as well beneath the silence;',
        'So instead of stepping away from your doubts,',
        'I only want to stay close beside you.',
        '',
        'Your weakness does not lower your worth,',
        'Nor diminish who you are;',
        'If anything, it only makes clearer',
        'That you are human, precious, and worth cherishing.',
        '',
        'That is why I blush, at the simple knowing,',
        'At the way you do not hide your soul;',
        'For there is a beauty no image can capture,',
        'Only a heart walking in truth.',
        '',
        'When you sent your photographs,',
        'I could not hide my wonder;',
        'Not because of looks alone or because of a name,',
        'But because you were in every picture.',
        '',
        'I saved them inside my memory,',
        'Like stars in a dark sky;',
        'So when the world grows heavy,',
        'I still have a reason to hope.',
        '',
        'Yet even when I cannot see your face,',
        'Your goodness remains with me;',
        'For real affection is not only in seeing,',
        'But in a heart that does not wish to wound.',
        '',
        'When you ask if I am already tired,',
        'Old wounds in me grow lighter;',
        'For that simple question asked with warmth',
        'Shows me that I matter.',
        '',
        'I should not compare you to the past,',
        'Yet I cannot deny the difference;',
        'Where others showed me pain,',
        'You showed me a gentle peace.',
        '',
        'If I blush under your care,',
        'It is because this is what I searched for;',
        'Not to be served out of pride,',
        'But to feel that I am not abandoned.',
        '',
        'You remind me that love can be clear,',
        'That it does not need to be full of hurt;',
        'That someone can be loved with respect,',
        'And cherished even in weakness.',
        '',
        'You never made me strong by force,',
        'You never rushed me into running;',
        'Little by little you helped me stand in the quiet,',
        'Like a candle guarded in the dark.',
        '',
        'When you say, "I am yours," with sincerity,',
        'My heart stirs in the stillness;',
        'For it is not possession bound by chains,',
        'But a choosing grounded in truth.',
        '',
        'When you speak with tenderness,',
        'I do not know where to place my heart;',
        'It is as if a once-stubborn heart becomes a child,',
        'Because at last someone is offering comfort.',
        '',
        'My blushing is not because I am fragile,',
        'But because the old coldness is fading;',
        'Like ice melting in the daylight',
        'When warmth finally arrives.',
        '',
        'I am not used to someone waiting for me,',
        'Not used to someone checking on me;',
        'So when you look for my presence,',
        'I blush with quiet joy.',
        '',
        'I am not used to someone defending me,',
        'Not used to someone receiving my weariness;',
        'So when you become a home at night,',
        'My heart thanks time itself.',
        '',
        'The heaviest part of what came before',
        'Was not just the wound but the loneliness;',
        'But you came with companionship,',
        'And taught me not to walk alone.',
        '',
        'Sometimes I cannot speak of this blushing,',
        'For I am shy before my own soul;',
        'But the truth is, you are the reason',
        'My heart has begun to know peace.',
        '',
        'I am not used to being loved rightly,',
        'Not used to being chosen with care;',
        'So when you show me goodness,',
        'My heart runs out of defenses.',
        '',
        'In every "take care" there is light,',
        'In every "go to sleep" there is tenderness;',
        'In every "eat something" there is meaning,',
        'In every "I am here" there is assurance.',
        '',
        'I do not belittle the little things,',
        'Because they keep a tired life alive;',
        'Simple words touched by care',
        'Can be stronger than a grand serenade.',
        '',
        'If I blush, it is because I have learned',
        'That love does not always arrive loudly;',
        'Sometimes it is this quiet care',
        'That says nothing yet carries meaning.',
        '',
        'You are the first to show me a kind of treatment',
        'That does not wound and does not drown;',
        'A way of caring marked by respect and caution,',
        'The kind I had long searched for in life.',
        '',
        'So when my face turns red in the quiet,',
        'It is not shallowness or mere excitement;',
        'It is a heart that has understood the truth,',
        'That at last it has been loved with respect.',
        '',
        'And if someone asks why I blush,',
        'I will answer from the depth of my soul;',
        'For in every way you treat me kindly,',
        'A part of me once lost begins to live again.',
        '',
        'So this blush is not only color,',
        'But a gift from a heart finally reached;',
        'For when you treated me rightly in the quiet,',
        'My whole being learned to blush in peace.'
      ]
    },
    {
      id: 10,
      title: 'An Pahingahan',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Dakol nang unos an satong nalampasan,', 'Sa sadit pa sanang panahon kan lakawan;'],
      mood: 'Peaceful',
      accentColor: '#2F7D6C',
      language: 'bikolano',
      lines: [
        'Dakol nang unos an satong nalampasan,',
        'Sa sadit pa sanang panahon kan lakawan;',
        'Mga bagyong baga dai dapat kayanon,',
        'Pero pigdaog ta sa pag-intindihan.',
        '',
        'May mga gabing puno nin pagduduman,',
        'May mga aldaw na mabug-at an kinaban;',
        'Pero sa tunga kan gabos na kahaditan,',
        'Nagdanay an satong pagkasararoan.',
        '',
        'Dai kita pinadaan sa payak na dalan,',
        'Dai man sa istoryang wara nin pagsubok;',
        'Pero kada bagyo na nag-abot sa sato,',
        'Mas nagin marigon an satong paglaomon.',
        '',
        'Ta an pusong pirming nag-aalirong,',
        'Dai basta natitinag nin kahaditan;',
        'An gugma na tinukod sa paggalang,',
        'Mas matibay kaysa kusog kan unos.',
        '',
        'Asin kun may maabot pang mga bagyo,',
        'Dai ako matatakot sa kalangitan;',
        'Ta nahiling ko na an satong katibayan,',
        'Sa mga unos na satong nalampasan.',
        '',
        'Sarong aldaw, kun may pag-iringatan,',
        'Dai kita matuturog na may kalungkutan;',
        'Ta bago pa man magsara an satong mata,',
        'Mahihiling ta an pag-intindihan.',
        '',
        'Dai kita matuturog na may kapungotan,',
        'Dai kita magpapadanay nin kasakitan;',
        'Ta an lambang hidwaan na mag-abot,',
        'Satong aayuson sa tahimik na paagi.',
        '',
        'An harong na gusto kong satong tukdon,',
        'Dai harong na puno nin giringgitan;',
        'Kundi harong na puno nin pagdamayan,',
        'Asin mga pulong na may paggalang.',
        '',
        'Dai an kusog kan kamot an maghahari,',
        'Dai man an galit an magdidikta;',
        'Kundi an kabubut-on na magdangog,',
        'Asin pusong marunong magsabot.',
        '',
        'Ta dakol ka nang pig-agihan sa buhay,',
        'Dakol nang unos an nag-abot saimo;',
        'Kaya kun may sarong bagay akong handom,',
        'Iyo an kapayapaan na dapat saimo.',
        '',
        'Kapayapaan sa tahaw kan kagab-ihon,',
        'Kapayapaan sa tahaw kan kabuwasan;',
        'Kapayapaan sa lambang pagmata,',
        'Asin sa lambang oras kan aldawan.',
        '',
        'Asin sa kada aldaw na magkasararo kita,',
        'Gusto kong maramdaman mo an katotoohan;',
        'Na dai ka nag-iisa sa paglakaw,',
        'Ta may kaagapay ka sa dalan.',
        '',
        'An mga pagsubok dai man mawawara,',
        'Ta parte iyan kan satong kinaban;',
        'Pero kada sarong ini na mag-abot,',
        'Mas lalo kitang magigin marigon.',
        '',
        'Kaya mahal, kun hilingon ta an bukas,',
        'Dai ko nahihiling an kahaditan lamang;',
        'Nahihiling ko an duwang pusong padagos,',
        'Na nagigin mas makusog sa kada panahon.'
      ],
      translationLines: [
        'We have already survived many storms,',
        'Even in the short stretch of our journey;',
        'Storms that seemed too heavy to bear,',
        'Yet we overcame them through understanding.',
        '',
        'There were nights full of doubt,',
        'And days when life was heavy;',
        'Yet in the midst of all that hardship,',
        'Our togetherness remained.',
        '',
        'We were not led along an easy road,',
        'Nor through a story without trials;',
        'But every storm that came to us',
        'Made our hope grow stronger.',
        '',
        'For a heart that keeps sheltering another',
        'Is not easily shaken by trouble;',
        'Love built on respect',
        'Is stronger than the force of any storm.',
        '',
        'And if more storms should come,',
        'I will not fear the sky;',
        'For I have seen our strength',
        'In the storms we have already passed.',
        '',
        'One day, if care remains between us,',
        'We will not sleep with sorrow;',
        'For before our eyes even close,',
        'We will find understanding.',
        '',
        'We will not go to sleep carrying anger,',
        'We will not let pain stay the night;',
        'For every conflict that comes to us',
        'We will mend in a quiet way.',
        '',
        'The home I want to build with you',
        'Is not a house full of shouting;',
        'But a house full of mutual care',
        'And words spoken with respect.',
        '',
        'The strength of the hand will not rule there,',
        'Nor will anger make the law;',
        'But a will that knows how to listen,',
        'And hearts that know how to understand.',
        '',
        'You have already gone through so much in life,',
        'So many storms have come to you;',
        'So if there is one thing I deeply hope for,',
        'It is the peace you deserve.',
        '',
        'Peace in the middle of night,',
        'Peace in the days ahead;',
        'Peace in every waking,',
        'And in every hour of daylight.',
        '',
        'And with every day we walk beside each other,',
        'I want you to feel the truth;',
        'That you do not walk alone,',
        'For someone walks with you.',
        '',
        'Trials will not disappear,',
        'For they are part of life;',
        'But every time one comes,',
        'We will grow stronger.',
        '',
        'So my love, when we look toward tomorrow,',
        'I do not see only hardship;',
        'I see two hearts still moving forward,',
        'Growing stronger with every season.'
      ]
    },
    {
      id: 11,
      title: 'Sa Lambang Pagsirang',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['An panahon pirming nagbabag-o,', 'An mga bulan pirming naglilipas;'],
      mood: 'Steadfast',
      accentColor: '#3B6C9B',
      language: 'bikolano',
      lines: [
        'An panahon pirming nagbabag-o,',
        'An mga bulan pirming naglilipas;',
        'Pero may mga butang sa kinaban,',
        'Na pirming pinipili sa kabuwasan.',
        '',
        'An mga dahon nalalagas sa kahoy,',
        'An mga alon nag-iiba nin dalan;',
        'Pero an pusong sigurado sa gugma,',
        'Dai basta nawawara sa panahon.',
        '',
        'Ta an kalipay dai pirming makusog,',
        'Dai pirming puno nin hararom na kilig;',
        'Kun minsan ini tahimik na liwanag,',
        'Na pirming nagdadanay sa kahiloman.',
        '',
        'May mga aldaw na puno nin katawa,',
        'May mga aldaw man na mabug-at;',
        'Pero an gugma na may katotoohan,',
        'Nagpapadagos maski sa kapagalon.',
        '',
        'Dai ta pirming mahihiling an bulalakaw,',
        'Dai pirming masiring an mga harana;',
        'Pero an puso na tunay na nagtitinindog,',
        'Pirming may dahilan para magdanay.',
        '',
        'May mga umagang ordinaryo sana,',
        'May kape sa lamisa asin tahimik na hangin;',
        'Wara man dakulang pangyayari sa aldaw,',
        'Pero may kapayapaan sa kaharongan.',
        '',
        'May mga gabing pareho kitang pagod,',
        'Na halos wara nang kusog magtaram;',
        'Pero an simpleng presensya sa harani,',
        'Baga pahingang haloy nang hinahanap.',
        '',
        'Dai an lambing pirming dakula,',
        'Dai man pirming puno nin surpresa;',
        'Kun minsan ini an simpleng pangumusta,',
        'Na may tunay na pag-ataman sa likod.',
        '',
        'Asin sa mga ordinaryong aldaw na iyan,',
        'Mas nasusubok an satong katibayan;',
        'Ta an gugma dai sana para sa piyesta,',
        'Kundi para man sa tahimik na panahon.',
        '',
        'Ta an buhay dai pirming pelikula,',
        'Dai pirming may awit sa likuran;',
        'Pero sa tunga kan normal na aldaw,',
        'Nag-uusbong an pinakatunay na gugma.',
        '',
        'May mga panahong magkakairingatan,',
        'May mga pulong na maling masabutan;',
        'Ta tawo kita, dai perpektong larawan,',
        'Asin may kahinaan an kada kabubut-on.',
        '',
        'May mga gabing gusto sana maghilom,',
        'May mga oras na gusto maglikay;',
        'Pero an gugma na marunong mag-antay,',
        'Dai nagdadalagan sa kahaditan.',
        '',
        'Ta an problema dai pirming kaaway,',
        'Kun minsan ini oportunidad na magsabot;',
        'Na mas aramon an nasa puso kan saro,',
        'Asin mas lalo pang magharani.',
        '',
        'Dai kita magpapatulog na may kapungotan,',
        'Kun kaya pang ayuson an satong kahimtangan;',
        'Ta an lambang tampuhan na masosolbar,',
        'Mas marhay kaysa pahabaan pa.',
        '',
        'An satong harong sa kabuwasan,',
        'Dai harong na puno nin giringgitan;',
        'Kundi harong na puno nin pagdangog,',
        'Asin pusong marunong magsabot.',
        '',
        'Ta an gugma bako sana pagbati,',
        'Dai sana kilig na marikas lumabay;',
        'Ini sarong desisyon sa kada aldaw,',
        'Na pirming ginbabalikan nin puso.',
        '',
        'An pagpili dai sana minsan nangyayari,',
        'Dai sana sa espesyal na okasyon;',
        'Ini ginagibo sa kada pagsirang,',
        'Asin sa kada pag-abot nin kagab-ihon.',
        '',
        'Pinipili taka kun masaya an aldaw,',
        'Pinipili taka kun mabug-at an panahon;',
        'Pinipili taka maski wara nin piyesta,',
        'Ta an pagpili dai nakaasa sa sitwasyon.',
        '',
        'Pinipili taka sa tunga kan katawa,',
        'Pinipili taka sa tunga kan luha;',
        'Ta an gugma na nakatindog sa oras,',
        'Dai basta natitinag nin bagyo.',
        '',
        'Asin kun magbag-o man an panahon,',
        'Kun magbag-o man an satong kahimtangan;',
        'An kabubut-on na pirming nagpupundo,',
        'Mahahanap giraray an dalan pabalik.',
        '',
        'Kaya dai ako nagpapadagos dahil madali,',
        'Dai man dahil pirming magayon an lakaw;',
        'Nagpapadagos ako ta may rason,',
        'Asin ika iyo an dakulang bahin kaini.',
        '',
        'Dai ko pinipili an sarong damgo sana,',
        'Dai ko pinipili an sarong larawan;',
        'Pigpipili ko an bug-os mong pagkatawo,',
        'Na may kusog, hiya, asin kahinaan.',
        '',
        'Pigpipili ko an saimong mga ngisi,',
        'Asin maski an mga luha sa kahiloman;',
        'Ta an gugma na tunay na nag-uugat,',
        'Dai namimili sana nin magagayon.',
        '',
        'Asin sa kada pagsirang nin adlaw,',
        'May sarong katotoohan na dai nagbabag-o;',
        'Maski ano pa an dalang panahon,',
        'Ika pa giraray an pipiliyon ko.',
        '',
        'Kaya kun haputon ako sa kabuwasan,',
        'Kun nano an sakong desisyon sa buhay;',
        'An sabat magigin pareho pa man giraray—',
        'Pinipili taka, sa kada aldaw.'
      ],
      translationLines: [
        'Time keeps changing,',
        'And the months keep passing;',
        'Yet there are things in this world',
        'Still chosen in the morning ahead.',
        '',
        'Leaves fall from the tree,',
        'And the waves change direction;',
        'But a heart that is sure of love',
        'Does not easily fade with time.',
        '',
        'Joy is not always loud,',
        'Nor always full of deep excitement;',
        'Sometimes it is a quiet light',
        'That remains within the stillness.',
        '',
        'There are days full of laughter,',
        'And days that feel heavy;',
        'But love grounded in truth',
        'Keeps going even through weariness.',
        '',
        'We do not always see shooting stars,',
        'Nor always speak in serenades;',
        'But a heart that truly stands',
        'Always has a reason to remain.',
        '',
        'Some mornings are simply ordinary,',
        'With coffee on the table and quiet air;',
        'Nothing great may happen in the day,',
        'Yet there is peace within the home.',
        '',
        'There are nights when we are both tired,',
        'With hardly any strength left to speak;',
        'Yet simple nearness beside each other',
        'Feels like a rest long sought.',
        '',
        'Tenderness is not always grand,',
        'Nor always full of surprises;',
        'Sometimes it is a simple greeting',
        'With real care behind it.',
        '',
        'And in such ordinary days,',
        'Our strength is tested even more;',
        'For love is not only for feast days,',
        'But also for quiet seasons.',
        '',
        'Life is not always a movie,',
        'Nor always music in the background;',
        'Yet in the middle of ordinary days,',
        'The truest love takes root.',
        '',
        'There will be times of misunderstanding,',
        'And words that are wrongly taken;',
        'For we are people, not perfect images,',
        'And every soul has weakness.',
        '',
        'There are nights when one only wants silence,',
        'And hours when one wants to pull away;',
        'Yet love that knows how to wait',
        'Does not run from hardship.',
        '',
        'Problems are not always enemies,',
        'Sometimes they are chances to understand;',
        'To know what is inside another heart,',
        'And to draw even nearer.',
        '',
        'We will not go to sleep carrying anger,',
        'While our situation can still be repaired;',
        'For every quarrel that can be resolved',
        'Is better than letting it drag on.',
        '',
        'The home waiting for us in the future',
        'Will not be a house full of shouting;',
        'But a house full of listening,',
        'And hearts that know how to understand.',
        '',
        'For love is not only a feeling,',
        'Nor just a thrill that quickly passes;',
        'It is a decision made every day,',
        'One the heart keeps returning to.',
        '',
        'Choosing does not happen only once,',
        'Nor only on special occasions;',
        'It is done at every dawn,',
        'And at every coming of night.',
        '',
        'I choose you when the day is joyful,',
        'I choose you when the season feels heavy;',
        'I choose you even without a celebration,',
        'For choosing does not depend on circumstance.',
        '',
        'I choose you in the middle of laughter,',
        'I choose you in the middle of tears;',
        'For love that stands through time',
        'Is not easily shaken by storms.',
        '',
        'And even if time should change,',
        'Even if our situation should change;',
        'The heart that keeps resting here',
        'Will still find the road back.',
        '',
        'I do not keep going because it is easy,',
        'Nor because the path is always beautiful;',
        'I keep going because there is reason,',
        'And you are a large part of it.',
        '',
        'I do not choose only a dream,',
        'Nor do I choose only an image;',
        'I choose your whole person,',
        'With strength, shyness, and weakness.',
        '',
        'I choose your smiles,',
        'And even your tears in the quiet night;',
        'For love that truly takes root',
        'Does not choose only what is pretty.',
        '',
        'And at every breaking of day,',
        'There is a truth that does not change;',
        'Whatever time may bring,',
        'You are still the one I will choose.',
        '',
        'So if I am asked in the days ahead',
        'What my decision in life will be,',
        'My answer will remain the same -',
        'I choose you, every day.'
      ]
    },
    {
      id: 12,
      title: 'Bago Mag-abot an Panahon',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Tahimik an simbahan sa kahiloman,', 'May kandilang nagsisindi sa altaran;'],
      mood: 'Hopeful',
      accentColor: '#8B5E3C',
      language: 'bikolano',
      lines: [
        'Tahimik an simbahan sa kahiloman,',
        'May kandilang nagsisindi sa altaran;',
        'An saldang nin adlaw sa mga bintana,',
        'Nagpapadanay nin init sa kapilyahan.',
        '',
        'May bulaklak na nakahilera sa dalan,',
        'Na siring tala sa tahaw kan kadlagan;',
        'An hangin marahan na naglalakaw,',
        'Siring awit na may dakulang kahulugan.',
        '',
        'An mga bangko wara pang nagkakahingko,',
        'An mga kampana wara pang nagtataram;',
        'Pero may sarong damgo sa kabubut-on,',
        'Na hinay na nagtutubo sa kahiloman.',
        '',
        'Sa dulo kan mahabang puting dalan,',
        'May larawan na pirming sakong handuman;',
        'Dai pa realidad, dai pa ngani bukas,',
        'Pero pirming buhay sa sakong kabubut-on.',
        '',
        'Ta kun magsara an mata sa kagab-ihon,',
        'Iyo an larawang pirming nagbabalikon;',
        'Simbahan, bulaklak, kandila, liwanag,',
        'Asin sarong pusong puno nin paglaomon.',
        '',
        'Asin sa likod kan pultang nabuksan,',
        'May sarong babae na tahimik nagtitinindog;',
        'Pig-aayos an buhok sa mahinay na paagi,',
        'Habang an pisngi may tagong kapulahan.',
        '',
        'May bulaklak siyang hawak sa kamot,',
        'Na baga pirming pinapahugot an paghinga;',
        'Dai dahil sa kahadlok nin kapahamakan,',
        'Kundi dahil sa hiya na dai maitago.',
        '',
        'May mga mata na nakatanaw saiya,',
        'Asin iyo lalo siyang nagpapamula;',
        'Kaya pirmi siyang nakatungo sa salog,',
        'Na baga may tinatagong katatawanan.',
        '',
        'Pero maski nakatungo sa kahiloman,',
        'An liwanag nagdadapo sa saiyang dagway;',
        'Asin sa lambang hakbang na pig-aandam,',
        'May bagong kabanatang gustong magsurat.',
        '',
        'Kun sain siya paduman sa tahaw kan dalan,',
        'Iyo man an lugar na sakong gin-aantabayan;',
        'Dai bilang katapusan kan satong istorya,',
        'Kundi sarong pahina sa mas mahabang lakawan.',
        '',
        'Asin habang nagtitindog sa altaran,',
        'Nagbabalik an mga lumang handumanan;',
        'An barkong nag-abot sa tahaw kan dagat,',
        'Na nagdala nin damgo sa kapatagan.',
        '',
        'An primerong bati sa tahaw kan hangin,',
        'An primerong ngisi na dai malilingawan;',
        'An primerong gabing nag-abot an istorya,',
        'Na baga duwang pusong haloy nang nagkilala.',
        '',
        'An mga gabing puno nin pag-istoryahan,',
        'An mga takot na hinay na binuksan;',
        'An mga sugat na dai pirming nahihiling,',
        'Pero pirming may bakas sa kabubut-on.',
        '',
        'Asin sa lambang oras na naglilipas,',
        'Mas nagin klaro an satong padulngan;',
        'Dai sa kapusukan o marikas na lakaw,',
        'Kundi sa pag-antay asin pag-intindihan.',
        '',
        'An mga bagyo man nag-abot sa sato,',
        'An mga pultahan minsan nagsarado;',
        'Pero maski harangan an satong dalan,',
        'An paglaom naghanap nin tulayan.',
        '',
        'Nahihiling ko an mga aldaw sa maabot,',
        'Mga umagang may kapeng nag-uusaan;',
        'Ikaw nag-aandam sa saimong mga handom,',
        'Ako man naglalakaw sa sakong katuyuhan.',
        '',
        'May mga gabing pareho kitang pagod,',
        'May mga oras na mabug-at an kinaban;',
        'Pero sa tahaw kan sarong simpleng lamisa,',
        'May kapayapaan sa satong kaharongan.',
        '',
        'May mga panahong magkakairingatan,',
        'Ta tawo kita asin dai mga anghel;',
        'Pero an lambang bagyo na mag-abot,',
        'Matatapos sa pag-intindi asin paggalang.',
        '',
        'May simbahan man sa satong kabuwasan,',
        'May mga dasal sa tahaw kan kagab-ihon;',
        'Asin sa lambang pasalamat na itatao,',
        'Mahihiling ko an saimong ngisi man.',
        '',
        'Dai ini damgo nin perpektong istorya,',
        'Dai man larawan nin buhay na wara bagyo;',
        'Kundi damgo nin duwang pusong tapat,',
        'Na pareho sanang nagpapadagos.',
        '',
        'Asin pagbalik ko sa tahaw kan dalan,',
        'Nahihiling taka na may bulaklak sa kamot;',
        'An pisngi mo pula sa tahaw kan hiya,',
        'Asin an mata mo pirming nakatungo.',
        '',
        'Baga gusto mong magngisi pero nagpipigil,',
        'Baga gusto mong tumangad pero nahihiya;',
        'Asin sa lambang hakbang mong paduman,',
        'Mas lalo akong napupuno nin tuwa.',
        '',
        'Pero pag-abot mo sa tahaw kan harani,',
        'Biglang naghinto an larawang nasa isip;',
        'Ta an simbahan, an altar, asin bulaklak,',
        'Nagdanay sana sa tahaw kan damgo.',
        '',
        'Ta dai pa ini aldaw nin kasalan,',
        'Dai pa ini oras nin panumpaan;',
        'Asin bago pa man kita mag-abot sa altar,',
        'May sarong butang akong gustong ipahiling.',
        '',
        'Asin sa tahaw kan tahimik na liwanag,',
        'Ako nakaluhod na may mahinay na ngisi;',
        'May payak na singsing sa tahaw kan kamot',
        'Dai bilang kadena, kundi direksyon.'
      ],
      translationLines: [
        'The church is quiet in stillness,',
        'Candles burn upon the altar;',
        'Sunlight through the windows',
        'Lays a gentle warmth upon the chapel.',
        '',
        'Flowers line the path,',
        'Like stars across the field;',
        'The wind walks softly,',
        'Like a song holding great meaning.',
        '',
        'The pews are still unbent by people,',
        'The bells have not yet spoken;',
        'Yet there is a dream in the heart',
        'Slowly growing in the silence.',
        '',
        'At the end of a long white path,',
        'There is an image I always keep;',
        'Not yet real, not even tomorrow,',
        'Yet alive within me always.',
        '',
        'For whenever I close my eyes at night,',
        'It is that image that returns;',
        'Church, flowers, candles, light,',
        'And one heart full of hope.',
        '',
        'And behind an opened door,',
        'A woman stands in quiet stillness;',
        'Fixing her hair in a gentle way,',
        'While hidden blush rests on her cheeks.',
        '',
        'There is a flower in her hand,',
        'And it seems to draw out her breath;',
        'Not from fear of disaster,',
        'But from shyness she cannot hide.',
        '',
        'Many eyes are looking at her,',
        'And that only makes her blush more;',
        'So she keeps her gaze lowered to the floor,',
        'As if holding back a smile.',
        '',
        'Yet even with her head bowed in the quiet,',
        'Light settles on her face;',
        'And with every step she prepares,',
        'A new chapter longs to be written.',
        '',
        'Wherever she is walking along that path,',
        'It is the same place I have been waiting for;',
        'Not as the end of our story,',
        'But as one page in a longer journey.',
        '',
        'And while standing at the altar,',
        'Old memories come back;',
        'The ship that came along the sea,',
        'Carrying a dream into the plain.',
        '',
        'The first greeting upon the wind,',
        'The first smile never forgotten;',
        'The first night our story arrived,',
        'As if two hearts had long known each other.',
        '',
        'The nights full of conversation,',
        'The fears slowly opened;',
        'The wounds not always seen,',
        'Yet always leaving marks on the soul.',
        '',
        'And with every passing hour,',
        'Our direction grew clearer;',
        'Not through haste or restless speed,',
        'But through waiting and understanding.',
        '',
        'Storms also came to us,',
        'Doors closed at times;',
        'Yet even when our road was blocked,',
        'Hope looked for a bridge.',
        '',
        'I can already see the days to come,',
        'Mornings with coffee shared together;',
        'You preparing for your dreams,',
        'I walking toward my own purpose.',
        '',
        'There will be nights when we are both tired,',
        'And hours when life feels heavy;',
        'Yet at one simple table,',
        'Peace will live within our home.',
        '',
        'There will be times of misunderstanding,',
        'For we are people and not angels;',
        'Yet every storm that comes',
        'Will end in understanding and respect.',
        '',
        'There will also be a church in our future,',
        'And prayers in the middle of night;',
        'And in every thanksgiving we offer,',
        'I will see your smile again.',
        '',
        'This is not a dream of a perfect story,',
        'Nor a picture of a life without storms;',
        'But the dream of two faithful hearts',
        'Both choosing to continue.',
        '',
        'And when I return to that path,',
        'I see you there with a flower in your hand;',
        'Your cheeks are red with shyness,',
        'And your eyes stay lowered.',
        '',
        'You seem to want to smile but hold it back,',
        'You seem to want to look up but feel shy;',
        'And with every step you take toward me,',
        'I fill more and more with joy.',
        '',
        'But when you come near,',
        'The picture inside my mind suddenly stops;',
        'For the church, the altar, and the flowers',
        'Remain only within the dream.',
        '',
        'For this is not yet the wedding day,',
        'Not yet the hour of vows;',
        'And before we ever reach the altar,',
        'There is one thing I want to show you.',
        '',
        'And in that quiet light,',
        'I am kneeling with a gentle smile;',
        'There is a simple ring in my hand,',
        'Not as a chain, but as a direction.'
      ]
    },
    
  ];

  getAllPoems(): ReadonlyArray<Poem> {
    return this.poems;
  }

  getPoem(id: number): Poem | undefined {
    return this.poems.find((poem) => poem.id === id);
  }

  getAdjacentPoems(id: number): { prev: Poem | null; next: Poem | null } {
    const idx = this.poems.findIndex((poem) => poem.id === id);

    if (idx === -1) {
      return { prev: null, next: null };
    }

    return {
      prev: idx > 0 ? this.poems[idx - 1] : null,
      next: idx < this.poems.length - 1 ? this.poems[idx + 1] : null
    };
  }

  getStanzas(lines: ReadonlyArray<string>): string[][] {
    return this.buildStanzas(lines);
  }

  getPoemContext(id: number): PoemContext | undefined {
    const poem = this.getPoem(id);

    if (!poem) {
      return undefined;
    }

    const { prev, next } = this.getAdjacentPoems(id);
    return {
      poem,
      prev,
      next,
      stanzas: this.getStanzas(poem.lines)
    };
  }

  private buildStanzas(lines: ReadonlyArray<string>): string[][] {
    const stanzas: string[][] = [];
    let currentStanza: string[] = [];

    for (const line of lines) {
      if (line === '') {
        if (currentStanza.length > 0) {
          stanzas.push(currentStanza);
          currentStanza = [];
        }

        continue;
      }

      currentStanza.push(line);
    }

    if (currentStanza.length > 0) {
      stanzas.push(currentStanza);
    }

    return stanzas;
  }
}
