import { Injectable } from '@angular/core';

export interface Poem {
  id: number;
  title: string;
  author: string;
  excerpt: string[];
  lines: string[];
  mood: string;
  accentColor: string;
}

export interface PoemContext {
  poem: Poem;
  prev: Poem | null;
  next: Poem | null;
  stanzas: string[][];
}

@Injectable({ providedIn: 'root' })
export class PoemsService {
  private readonly poems: ReadonlyArray<Poem> = [
    {
      id: 1,
      title: 'An Barkong Nag-abot',
      author: 'Benedict Ellie A. Lowell | BSCS 3-A',
      excerpt: ['Sa tahaw kan gabing puno nin kadikloman,', 'May barkong nag-abot sa tahimik na baybayan;'],
      mood: 'Reflective',
      accentColor: '#2E8B57',
      lines: [
        'Sa tahaw kan gabing puno nin kadikloman,',
        'May barkong nag-abot sa tahimik na baybayan;',
        'Nagdanay ako sa harani kan pantalan,',
        'Dai aram kun biyaya o panibagong kasakitan.',
        '',
        'Dakol nang bagyo an nag-agi sa karagatan,',
        'Dakol nang saad an tinabunan nin kalipatan;',
        'Dakol nang pusong ginadan nin kasalanan,',
        'Asin dakol nang mata an napuno nin kalungkutan.',
        '',
        'Nung marungog ko an saimong dating kaagihan,',
        'Napuno ako nin dakulang pagduduman;',
        'Ta may mga taong naglalaro sa paglaoman,',
        'Asin nag-iiwan nin bakas na dai malipatan.',
        '',
        'Kaya ako nagdanay sa tahaw kan pantalan,',
        'Dai nagdadalagan sa bagong kapalaran;',
        'Mas marhay nang magbantay sa kalayuan,',
        'Kaysa mahulog naman sa dating kasakitan.',
        '',
        'Pero bako an hangin an nagpoon nin kahadean,',
        'Bako man an alon sa tahaw kan baybayan;',
        'Sa gabing tahimik asin puno nin kahiloman,',
        'Ikaw an nagtao kan pinakaunang kahadean.',
        '',
        'Sarong simpleng pagbati na may kalambingan,',
        'Wara nin pilit, wara nin kapalaluan;',
        'Pero sa puso kong puno nin pagduduman,',
        'Nagtanom iyan nin munting paglaoman.',
        '',
        'Ipinahiling ko saimo an sakuyang mga gibuhon,',
        'Mga proyekto, obligasyon, asin mga handumon;',
        'Patunay na dai ako basta nawawara sa panahon,',
        'Kundi nakikipaglaban sa sakuyang mga pangitngiton.',
        '',
        'Asin habang ako nagkukwento kan mga pasanon,',
        'Ikaw nagdangog na may dakulang pagdangogon;',
        'An mga sugat na tago sa sakuyang kabubut-on,',
        'Nasasabutan mo maski wara pang pagtaramon.',
        '',
        'Duman naghinay an dating mabagsik na alon,',
        'Asin naglinaw an madiklom na panahon;',
        'Ta minsan palan, an tunay na pagbangon,',
        'Nagtitikang sa pusong may dakulang pagdangogon.',
        '',
        'Kaya kun may maghapot kun sain nagpoon an rason,',
        'Dai sa matam-is na saad o mga tataramon;',
        'Kundi sa barkong nag-abot sa tahaw kan alon,',
        'Asin sa sarong "hello" na nagin sakuyang paglaomon.'
      ]
    },
    {
      id: 2,
      title: 'That One Night We Talked',
      author: 'Benedict Ellie A. Lowell | BSCS 3-A',
      excerpt: ['Sa gabing tahimik asin may kahiloman,', 'Nag-istoryahan kita na may kaluwasan;'],
      mood: 'Introspective',
      accentColor: '#4F7CAC',
      lines: [
        'Sa gabing tahimik asin may kahiloman,',
        'Nag-istoryahan kita na may kaluwasan;',
        'Dai sindaing magpakusog o magpanggaran,',
        'Kundi duwang kaluluwang may kakulangan.',
        '',
        'May gutom sa puso na dai maibitaran,',
        'May handom na piglalaban sa kahiditan;',
        'Nagtaram kita na wara nang pag-iingatan,',
        'Siring baga kita nagkilala na nin kaidtoan.',
        '',
        'An sakuyang pader mataas na hararoman,',
        'Tinukod nin taon nin pagkapirdihan;',
        'Bawat tipak may bakas nin kasakitan,',
        'Asin bawat bato may ngaran na kapalpakan.',
        '',
        'Dakol nang nagtingin sa sakuyang hararoman,',
        'Dakol man an nagsubok nin pagsulod duman;',
        'Pero nagbalik sinda sa parehong kadiklanan,',
        'Na wara man sana nin nabag-o sa sakuyang kamugtakan.',
        '',
        'Pero sa gabing may tahimik na kahadean,',
        'Dai mo ginpusol an pader sa pakikigbaan;',
        'Sarong taram mo sana na may katotoohan,',
        'Asin an hararoman nagkaigwa nin bitakan.',
        '',
        'Habang pigdadangog ko an saimong kaagihan,',
        'Nabati ko an tagong lungkot sa kada tataramon;',
        'May ngisi sa imo pero may kahiditan,',
        'Na tinatago sa likod kan saimong katatawanan.',
        '',
        'Pig-istorya mo an mga suliran sa harong nindoan,',
        'An mga gabing puno nin pag-aalitan;',
        'An mga taram na nagdudulot nin kasakitan,',
        'Asin an paglaom na pirming sinusubukan.',
        '',
        'Asin sa lambang detalye kan saimong istoryahan,',
        'Nabati ko an saimong pagkapagal asin kahinaan;',
        'Dai bilang kapalpakan o kakulangan,',
        'Kundi bilang pusong may dakulang pinasanan.',
        '',
        'Duman ko nasabutan an saimong kalagayan,',
        'Na sa likod kan kusog may nakatagong kalungkutan;',
        'Asin sa likod kan ngisi may pag-uusisa man,',
        'Kun may matitirang tawo na dai magpapabayaan.',
        '',
        'Kaya an gabing yaon dai ko malilipatan,',
        'Ta dai sana kita nagkaigwa nin istoryahan;',
        'Duwang pusong gutom sa pag-intindihan,',
        'An nag-abot asin nagkaigwa nin kahadean.'
      ]
    },
    {
      id: 3,
      title: 'An Tulay sa Kadikloman',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Nag-abot an aldaw nin dakulang pagsubok,', 'An mga pultahan pinasara sa pagdali;'],
      mood: 'Hopeful',
      accentColor: '#6A1B9A',
      lines: [
        'Nag-abot an aldaw nin dakulang pagsubok,',
        'An mga pultahan pinasara sa pagdali;',
        'An mga dalan pinutol nin kahiditan,',
        'Asin an paglaom pigsubok sa kahiloman.',
        '',
        'Duwang puso an pinalayo nin kapalaran,',
        'Duwang ngaran an pig-ulang sa kahadean;',
        'An mga taram na dating madaling abuton,',
        'Nagin bihira sa lambang panahon.',
        '',
        'Sa sarong kisapmata nagbago an sitwasyon,',
        'An mga oras nagin puno nin paghulaton;',
        'An dating kasanayan nagin alaala lamang,',
        'Asin an kada minuto may kabug-atan.',
        '',
        'May mga nagsiring na tapos na an lakaw,',
        'Na an barkong naglayag mapapara sa dagat;',
        'Na an bagyo sapat na para magpahingalo,',
        'Asin an kahadean dai na magduro.',
        '',
        'Pero dai ninda aram an katotoohan,',
        'Na may mga pusong dai basta sumusuko;',
        'Na kun sarhan man ninda an sarong dalan,',
        'May matutukod na bago sa kadikloman.',
        '',
        'Habang an iba nagtutukod nin harangon,',
        'May iba man na nagtutukod nin tulayon;',
        'Tahimik sana, wara nin paghambogon,',
        'Pero puno nin kusog asin katuyuhan.',
        '',
        'Sa tahaw kan gabing puno nin kahiditan,',
        'Nagkaigwa nin mga kamot na handang magbulig;',
        'Mga kaibigang nagtindog sa kahadean,',
        'Asin nagtao nin liwanag sa kadikloman.',
        '',
        'May mga mensaheng dai dapat mawara,',
        'May mga pangungusap na dapat maabot pa;',
        'Ta an puso dai man sinusukat nin distansya,',
        'Kundi sa pagpadagos kan saiyang paglaom.',
        '',
        'Asin sa kada tulay na naitukod duman,',
        'May bagong kusog na pigtao kan panahon;',
        'Na bako palan gabos nadadaog nin harangon,',
        'Kun an katuyuan puno nin katotoohan.',
        '',
        'Nahiling ko man an kusog sa saimong puso,',
        'Maski pigpapasan mo an sadiring bagyo;',
        'Maski pigpipilit ka kan mga pagsubok,',
        'Nagpapadagos ka gihapon sa pag-abot.',
        '',
        'Asin sa lambang aldaw nin paghulaton,',
        'Mas lalo kong nasabutan an kahulugan;',
        'Na an tunay na koneksyon sa duwang kaluluwa,',
        'Dai basta napuputol nin simpleng problema.',
        '',
        'Ta may mga butang na lampas sa harangon,',
        'Lampas sa kadikloman asin kalayuan;',
        'Mga bagay na nabubuhay sa paglaom,',
        'Asin nagtitinindog sa tahaw kan panahon.',
        '',
        'Kaya kun may maghapot kun pano ini nabuhay,',
        'Kun pano ini nagduro maski may kadikloman;',
        'Masasabi ko sana sa tahaw kan buhay—',
        'Pigsarad ninda an mga pultahan,',
        'Pero an mga puso nakahanap nin tulayon.'
      ]
    },
    {
      id: 4,
      title: 'Kun Magduro an Panahon',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['May siyudad na tinukod sa karagatan,', 'Napapalibutan nin bakal na harangan;'],
      mood: 'Resolute',
      accentColor: '#2C3E50',
      lines: [
        'May siyudad na tinukod sa karagatan,',
        'Napapalibutan nin bakal na harangan;',
        'Dakol nang hukbo an nag-abot sa atubangan,',
        'Pero gabos nagbalik sa kadikloman.',
        '',
        'Nagngalitngit an langit sa kahiloman,',
        'Naglinog an daga sa kapatagan;',
        'An mga bandera naglayog sa kalangitan,',
        'Siring tanda nin dakulang gerahan.',
        '',
        'Dakol an pamangkot sa atubangan,',
        'Dakol man an paghusgar sa kahimtangan;',
        'Pig-uukian an lambang katuyuhan,',
        'Asin pigsusukol an katibayan.',
        '',
        'An mga tore nagtindog sa kalayuan,',
        'An mga pader makusog sa katibayan;',
        'Pigbantayan ini nin dating kasakitan,',
        'Asin pinatibay nin pagduduman.',
        '',
        'Dakol nang alon sa karagatan,',
        'Dakol nang bagyo sa kalangitan;',
        'Pero an siyudad nagdanay sa katindugan,',
        'Maski pig-uuran nin kahaditan.',
        '',
        'An mga agi sa tahaw kan kapatagan,',
        'Napuno nin usok asin kadikloman;',
        'Pig-uukian an lambang pundasyon,',
        'Para masukol an tunay na katibayan.',
        '',
        'Asin sa tunga kan maingay na gerahan,',
        'May tahimik na hagad sa kalayuan;',
        'Dai ini kulog kan karagatan,',
        'Kundi hagakgak nin kabubut-an.',
        '',
        'Ta sa likod kan mga katatawanan,',
        'May tagong bakas nin kalungkutan;',
        'Sa likod kan mga simpleng tataramon,',
        'May pusong puno nin pagduduman.',
        '',
        'Nag-abot an tigsik nin panahon,',
        'Siring amihan sa tahaw kan kabubut-on;',
        'May pamangkot na dai lubos na nagtataramon,',
        'Pero mababati sa tahaw kan kahiloman.',
        '',
        'Siring an bulan sa tahaw kan karagatan,',
        'Na pirming natatabunan nin kadikloman;',
        'May kahadlok na magin sarong alaalon,',
        'Na madara sana nin panahon.',
        '',
        'May pantalan sa tahaw kan baybayon,',
        'Na pirming naghuhulat nin pagbalikon;',
        'Dai ini nagdadalagan sa direksyon,',
        'Dai man napapaurag sa panahon.',
        '',
        'An mga parola sa tahaw kan baybayon,',
        'Pirming may sindi sa lambang kahiloman;',
        'Dai ninda gin-aapura an mga layagon,',
        'Kundi piggigiya sinda sa paroroonan.',
        '',
        'Asin sa tunga kan usok kan gerahan,',
        'May tahimik na saad na nabuoan;',
        'Dai bilang kulog sa kalangitan,',
        'Kundi siring bituing may katindugan.',
        '',
        'Ta an tunay na paglaom may katibayan,',
        'Dai basta nalulusaw sa kahaditan;',
        'Maski magngalitngit an kalangitan,',
        'Nagpupundo giraray sa kabubut-an.',
        '',
        'An siyudad nagtinindog sa kadagaan,',
        'An mga pader nakaabot sa katapusan;',
        'Pero may sarong butang na lampas sa husgaran,',
        'Na dai masukol nin ano mang sukolan.',
        '',
        'Kaya sa tahaw kan gabing may kahiloman,',
        'Sa tunga kan bagyo asin gerahan;',
        'May sarong puso na nagpili nin pag-antayan,',
        'Maski magduro pa an panahonan.'
      ]
    },
    {
      id: 5,
      title: 'The Girl Who Spoke Like Rain',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Some flowers arrive with thunder and flame,', 'Demanding the world to remember their name;'],
      mood: 'Tender',
      accentColor: '#C0829D',
      lines: [
        'Some flowers arrive with thunder and flame,',
        'Demanding the world to remember their name;',
        'But you were the hush at the close of the day,',
        'A soft little star that refused to fade away.',
        '',
        'You entered my life without banners unfurled,',
        'Without any wish to astonish the world;',
        'Yet somehow the silence you carried with grace,',
        'Left traces of light in every place.',
        '',
        'The first time I heard your voice through the air,',
        'I forgot every burden and every despair;',
        'It floated so gently through distance and time,',
        'Like a hymn that had wandered from Heaven sublime.',
        '',
        'I listened again, then listened once more,',
        'As though it were waves on a faraway shore;',
        'For every soft syllable fell from above,',
        'Like rain teaching deserts the meaning of love.',
        '',
        'There was sweetness concealed in the way that you spoke,',
        'In the pauses between every word that awoke;',
        'And even your shyness, reluctant to stay,',
        'Made my guarded old heart slowly drift your way.',
        '',
        'For behind every smile there lingered a fear,',
        'A shadow that quietly followed you near;',
        'A wound that reminded your spirit each day,',
        'That not every person is destined to stay.',
        '',
        'I noticed it there in the things left unsaid,',
        'In the caution that walked where your confidence tread;',
        'Yet somehow those fragments made you more real,',
        'A portrait no painter could perfectly reveal.',
        '',
        'You never pretended to shine like the sun,',
        'Or claimed to be flawless before anyone;',
        'Yet the honesty woven through all that you are,',
        'Made you brighter than many who tried to shine far.',
        '',
        'And every small detail I happened to see,',
        'Became unexpectedly precious to me;',
        'The things you called ordinary, simple, or slight,',
        'Somehow transformed into sources of light.',
        '',
        'Your laughter was gentle, your manner was kind,',
        'Leaving echoes that lingered long after in mind;',
        'Like pages revisited time after time,',
        'Still beautiful long after reading each line.',
        '',
        'Then one day you trusted me just enough,',
        'To share little pieces of yourself and your love;',
        'A glimpse through a window carefully drawn,',
        'A portrait illuminated by dawn.',
        '',
        'And when those photographs finally came through,',
        'The world seemed determined to pause for a view;',
        'I saved every image before I could think,',
        'Afraid that a moment might vanish in a blink.',
        '',
        'Not because beauty was all that I saw,',
        'Nor because perfection inspired me with awe;',
        'But because every picture carried your name,',
        'And knowing their owner made them impossible to tame.',
        '',
        'There are sunsets more brilliant than gold in the sky,',
        'And wonders that travelers journey to find;',
        'Yet none of them ever persuaded my heart,',
        'To linger the way you did from the start.',
        '',
        'For beauty alone is a fleeting delight,',
        'A candle that flickers away in the night;',
        'But kindness and softness endure through the years,',
        'Remaining through triumphs and remaining through tears.',
        '',
        'And so when I think of the path that began,',
        'I remember no grand or remarkable plan;',
        'Only a shy little voice reaching over the sea,',
        'And somehow finding its way directly to me.',
        '',
        'If anyone asks what first captured my eyes,',
        'It wasn\'t mere beauty beneath distant skies;',
        'It was a gentle soul learning slowly to trust,',
        'And a quiet young heart that I treasure because it is just... you.'
      ]
    },
    {
      id: 6,
      title: 'At 11:28 PM',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['There are hours that pass like forgotten rain,', 'And hours that vanish without leaving a name;'],
      mood: 'Hopeful',
      accentColor: '#5B7C99',
      lines: [
        'There are hours that pass like forgotten rain,',
        'And hours that vanish without leaving a name;',
        'But one quiet moment still lives in my mind,',
        'Like a star that the years will never leave behind.',
        '',
        'The day had been long with its battles and noise,',
        'Filled with responsibilities, burdens, and choice;',
        'Yet somewhere beyond all the things left to do,',
        'My thoughts kept returning to only you.',
        '',
        'Five days had wandered since words took their flight,',
        'Crossing uncertain horizons that night;',
        'And though I stood firm in the promise I\'d made,',
        'I knew some answers cannot simply be weighed.',
        '',
        'For hope is a traveler careful and slow,',
        'A river that chooses its own way to flow;',
        'And hearts that have suffered are often afraid,',
        'To step toward the light after living in shade.',
        '',
        'So I waited in patience, as calm as I could,',
        'Believing that rushing would do no good;',
        'For flowers unfold in their season and time,',
        'Not because someone demands they should climb.',
        '',
        'Then came a moment both simple and small,',
        'No thunder, no trumpet, no grandness at all;',
        'Just a message appearing in quiet delight,',
        'Like dawn finding mountains at the end of the night.',
        '',
        'And somehow the world grew lighter to bear,',
        'As though every burden dissolved into air;',
        'The answer I\'d hoped for, gentle and true,',
        'Arrived carrying pieces of Heaven in view.',
        '',
        'No treasure I\'ve held could compare with that gift,',
        'No victory ever produced such a lift;',
        'For what reached my heart in that silent embrace,',
        'Was something no title or trophy could replace.',
        '',
        'The clock kept its rhythm as always before,',
        'Unaware it had opened a brand-new door;',
        'While somewhere beneath that ordinary sky,',
        'A dream quietly learned it was allowed to fly.',
        '',
        'And so before sleep gently carried me away,',
        'The finest gift found me at the close of the day;',
        'At exactly eleven twenty-eight that night,',
        'You gave one small answer—',
        '',
        'And turned darkness to light.'
      ]
    },
    {
      id: 7,
      title: 'An Langit na Nagbagsak nin Duwang Beses',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Naghinayon pa sana an karagatan,', 'Pagkatapos kan dating kahaditan;'],
      mood: 'Hopeful',
      accentColor: '#E67E22',
      lines: [
        'Naghinayon pa sana an karagatan,',
        'Pagkatapos kan dating kahaditan;',
        'Pero nagtipon giraray an kadikloman,',
        'Sa tahaw kan tahimik na kalangitan.',
        '',
        'May bagyong dai nagtaram nin ngaran,',
        'May unos na dai naghatod nin hudyatan;',
        'Basta sana nag-abot sa baybayon,',
        'Asin nagdala nin dakulang kahaditan.',
        '',
        'An mga alon nagkusog sa karagatan,',
        'An mga panganod nagtipon sa kalangitan;',
        'Siring baga an kapalaran mismo,',
        'Nagpili na subukon an kahadean.',
        '',
        'May mga tore na nagkaigwa nin liwanag,',
        'May mga bantay na nagmulat sa kalayuan;',
        'Asin an tahimik na dalan sa kagab-ihon,',
        'Biglang napuno nin pag-aalangan.',
        '',
        'Naglinog an puso sa kahiloman,',
        'Siring dahon na ginuyod kan habagat;',
        'Ta may kahadlok na an sarong paglaoman,',
        'Mahadit sa tunga kan kadikloman.',
        '',
        'Kaya nagtukod giraray nin tulayan,',
        'Sa tahaw kan dagat asin kalayuan;',
        'Dai para sa giringgitan o kadagaan,',
        'Kundi para sa pagpadagos kan kahadean.',
        '',
        'May mga dalan na nakalihim sa kagabsan,',
        'May mga parola sa tahaw kan baybayon;',
        'Asin maski nagngalitngit an kalangitan,',
        'Nagdanay pa giraray an katuyuhan.',
        '',
        'Ta an tunay na paglaom dai maruruba,',
        'Maski pig-uuran nin dakulang bagyo;',
        'Dai ini basta nalulunod sa alon,',
        'Kun may pusong pirming nag-aantabayon.',
        '',
        'Asin sa tunga kan usok kan gerahan,',
        'May sarong kamot na dai bumitawan;',
        'Maski nag-uuran nin kahaditan,',
        'Dai nagluya an saiyang katindugan.',
        '',
        'Nag-abot an gabi na may kahiloman,',
        'Puno nin pangutana asin pagduduman;',
        'Pero sa laog kan tahimik na kabubut-on,',
        'May sinding dai mahayup sa panahon.',
        '',
        'Siring an buwan sa tahaw kan karagatan,',
        'Na pirming nagbabalik sa kadikloman;',
        'Maski matabunan nin mga panganod,',
        'Dai nawawara an saiyang kahadeanon.',
        '',
        'May mga tulay na dai nakikita nin mata,',
        'May mga dalan na dai nahihiling nin iba;',
        'Pero an mga ini nagtitinindog,',
        'Sa tahaw kan dakulang paglaomon.',
        '',
        'Asin may sarong payak na handumanon,',
        'Na pinanday sa tunga kan kahiloman;',
        'Dai sa bakal, dai sa bato man,',
        'Kundi sa pag-antay asin kabubut-on.',
        '',
        'Ta may mga bagyo na dai tinatabangan,',
        'Nin kusog o mataras na armasan;',
        'Kundi nin pusong dai nagdadalagan,',
        'Maski pig-uuran nin kahaditan.',
        '',
        'An langit nagbagsak nin duwang beses,',
        'Sa tahaw kan satong kinabubuhian;',
        'Pero an mga bituin dai nagkararaot,',
        'Sa tahaw kan satong kahadeanon.',
        '',
        'Asin pagluwas kan bagyo sa kalangitan,',
        'Nagdanay pa giraray an katindugan;',
        'Ta an mga bagay na may kahulugan,',
        'Dai basta natatapos sa kahaditan.',
        '',
        'Kaya kun may aldaw na dai malilipatan,',
        'Iyo an gabing puno nin kadikloman;',
        'Ta maski nagbagsak an langit nin duwang beses,',
        'Nag-abot kita sa parehas na kahadeanon.'
      ]
    },
    {
      id: 8,
      title: 'An Rason na Dai Nauubos',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Kun haputon ako kun nano an rason,', 'Nano an pinaghalinan kan kahadeanon;'],
      mood: 'Introspective',
      accentColor: '#A0835C',
      lines: [
        'Kun haputon ako kun nano an rason,',
        'Nano an pinaghalinan kan kahadeanon;',
        'Dai ako mataram nin sarong bagay lamang,',
        'Ta dakol siyang bitbit na kahulugan.',
        '',
        'Dai siya nag-abot siring kusog na bagyo,',
        'Dai man siring kulog sa kalangitan;',
        'Nag-abot siya siring hinay na alon,',
        'Na marahay sanang naghahaplos sa baybayon.',
        '',
        'May mga tawo na naghihiling nin kusog,',
        'May mga tawo na naghihiling nin dangal;',
        'Pero may kagayunan sa kalambingan,',
        'Na dai masusukol nin ano mang sukatan.',
        '',
        'An saiyang mga tataramon na mahinay,',
        'Siring habagat sa tahaw kan kagabsan;',
        'Dai nag-uutob nin dakulang giringgitan,',
        'Pero nakakahiling nin kapayapaan.',
        '',
        'Asin sa lambang aldaw na nag-aagi,',
        'Mas lalo kong nasasabutan an katotoohan;',
        'Na an pinakamalumoy na mga puso,',
        'An pirming may pinakadakulang kahulugan.',
        '',
        'An primerong beses na narungog ko siya,',
        'Siring naghinayon an bilog na kinaban;',
        'An mga alon nagdanay sa karagatan,',
        'Asin naghilom an lambang kaguluhan.',
        '',
        'An saiyang boses dai sana sarong awit,',
        'Dai man sana sarong ordinaryong tataramon;',
        'Siring ini harong sa tahaw kan bagyo,',
        'Na pirming may sinding paglaomon.',
        '',
        'Asin sa lambang pulong na naglalakaw,',
        'May kalambingan na dai matutumbasan;',
        'Siring bulan na naghahaplos sa dagat,',
        'Sa tahaw kan tahimik na kagabsan.',
        '',
        'Dakol na awit an pigdangog kan talinga,',
        'Dakol nang himig an nag-agi sa panahon;',
        'Pero may mga boses na nag-iiwan,',
        'Nin permanente nang handumanon.',
        '',
        'Iyo an klase nin liwanag na dai masilaw,',
        'Dai siring adlaw na makusog an sindi;',
        'Kundi siring bituing tahimik sa langit,',
        'Na pirming presente sa kagab-ihon.',
        '',
        'Sa primerong paghiling, siya mahihiyaon,',
        'Siring bulaklak sa tahaw kan kagabsan;',
        'Pero an mga bulaklak na mahihiyaon,',
        'An pirming may pinakamarahay na kahumotan.',
        '',
        'Sa likod kan mahinay niyang pagngisi,',
        'May kasaysayan nin dakulang pakigbato;',
        'Mga bagyong nag-agi sa saiyang dagat,',
        'Asin mga unos na dai niya pinili.',
        '',
        'May mga sugat na dai nakikita nin mata,',
        'May mga kahadlok na dai pirming natataram;',
        'Pero nagpadagos siya sa paglakaw,',
        'Maski mabug-at an pinapasan.',
        '',
        'An kusog dai pirming maingay,',
        'Dai pirming may espada o bandila;',
        'Kun minsan ini sarong pusong pagod,',
        'Na nagpapadagos maski may luha.',
        '',
        'Asin iyo an kusog na nahiling ko saiya,',
        'Dai an kusog kan giringgitan o kadagaan;',
        'Kundi an kusog kan sarong kaluluwa,',
        'Na nagpupundo maski sa kahaditan.',
        '',
        'May mga kuta na tinukod nin panahon,',
        'Mga pader na pinatibay nin kasakitan;',
        'Asin may mga pultahan na dai basta,',
        'Nagbubukas sa lambang nag-aabotan.',
        '',
        'Pero hinay-hinay nagbukas an pultahan,',
        'Dai sa kusog o pagpilit man;',
        'Kundi sa tahaw kan padagos na panahon,',
        'Asin sa simpleng katotoohan.',
        '',
        'An pagtiwala siring tanom sa umahan,',
        'Dai nag-uusbong sa sarong kagab-ihon;',
        'Pig-aalagaan ini nin pag-antay,',
        'Asin nin malinig na katuyuhan.',
        '',
        'Asin sa lambang istoryang ibinahagi,',
        'Sa lambang kahadlok na ipinahiling;',
        'Mas lalo kong nasabutan an karangalan,',
        'Kan pagtiwalang ipinagkaloob sa sakuya.',
        '',
        'Ta an pinakamarahay na mga regalo,',
        'Dai nakukuyog sa kahon o laso;',
        'Kun minsan ini an simpleng pagtiwala,',
        'Kan sarong pusong dakol nang pinag-agihan.',
        '',
        'May mga tawo na nag-aagi sana,',
        'Siring alon na nag-iiwan nin bakas;',
        'Pero may mga tawo man na nagbabago,',
        'Kan direksyon kan satong dagat.',
        '',
        'Bago siya, dakol an tahimik na kagab-ihon,',
        'Dakol an mga adlawan na wara nin kulay;',
        'Pero may mga tawo talagang nag-aabot,',
        'Na may dalang bagong pagsirang.',
        '',
        'Dai niya aram an gabos niyang epekto,',
        'Sa tahaw kan sakuyang kabubut-on;',
        'Kung pano an sarong simpleng mensahe,',
        'Nakakapadanay kan kaguluhan.',
        '',
        'Asin sa tahaw kan lambang pagsubok,',
        'May rason na para magpadagos;',
        'Dai ta pirming madali an dalan,',
        'Pero mas marahay an paglakaw.',
        '',
        'Ta may mga paglaom na mas nagkakusog,',
        'Kun may sarong tawo na kaiba;',
        'Siring barkong mas kampante maglayag,',
        'Kun may nakikitang parola.',
        '',
        'Kaya kun haputon ako kun nano an rason,',
        'Dai sapat an sabat na "ta magayon siya";',
        'Ta dakol pang bulan sa kalangitan,',
        'Asin dakol pang bulaklak sa kadlagan.',
        '',
        'Dai man sapat an sabat na "ta malumoy siya,"',
        'Maski katotoohan man iyan;',
        'Ta an rason dai nakukulong,',
        'Sa sarong linya nin tataramon.',
        '',
        'An rason iyo an bug-os niyang pagkatawo,',
        'An saiyang ngisi asin kalungkutan;',
        'An saiyang kusog asin kahinaan,',
        'Asin an saiyang bug-os na katawuhan.',
        '',
        'An rason iyo an paagi niyang magpadagos,',
        'Maski pig-uuran nin kahaditan;',
        'An paagi niyang magliwanag,',
        'Maski napapalibutan nin kadikloman.',
        '',
        'Kaya kun may sarong katotoohan lamang,',
        'Na gusto kong dal-on sa lambang panahon;',
        'Iyo ini: dai ako nahulog sa sarong detalye—',
        'Nahulog ako sa bug-os niyang pagkatawo.'
      ]
    },
    {
      id: 9,
      title: 'An Pamula kan Pusong Dai Nasanay',
      author: 'Adriaan M. Dimate | BSCS 4-A',
      excerpt: ['Dai ko aram kun taano ako namumula sa kahiloman,', 'Kun taano nagrurugpa an puso sa simpleng tataramon;'],
      mood: 'Tender',
      accentColor: '#6C3483',
      lines: [
        'Dai ko aram kun taano ako namumula sa kahiloman,',
        'Kun taano nagrurugpa an puso sa simpleng tataramon;',
        'Baga may bulan na nagtutukar sa sakuyang kabubut-on,',
        'Asin may liwanag na nagbababa sa sakuyang panahon.',
        '',
        'Dai man ini dahil sa kagayunan lamang sa atubangan,',
        'Dai man dahil sa ngisi na siring bulaklak sa kadlagan;',
        'Kundi dahil sa pag-abot nin sarong kahadean,',
        'Na dai ko pa lubos namidbidan sa dating kaagihan.',
        '',
        'Ta may mga bagay na sadit sa ibang pagmamasdan,',
        'Pero sa pusong napagal, nagigin dakulang kahulugan;',
        'Sarong “kumain ka na?” sa tunga kan aldawan,',
        'Nagin kandila sa dating malamig na kahiloman.',
        '',
        'Sarong “magpahinga ka” na may tunay na pag-aram,',
        'Dai sana tataramon na nag-agi sa talinga;',
        'Kundi siring habagat na humaplos sa kaluluwa,',
        'Asin nagturo na may nag-aalala pa sa sakuya.',
        '',
        'Kun minsan an puso dai namumula sa pagharana,',
        'Kundi sa pag-abot nin pag-ataman na tama;',
        'Ta an bagay na dapat normal sa kinaban,',
        'Sa napabayaan na puso, nagigin katingalahan.',
        '',
        'Dai ko sanang inisip na an simpleng paglingap,',
        'Makakapagpaalon sa tahimik kong dagat;',
        'Pero kan ika nag-abot na may pag-iingat,',
        'An dating pader nagkaigwa nin bitak.',
        '',
        'An mga mata ko nasanay sa paglikay,',
        'An puso ko nasanay sa pag-antabay;',
        'Pero kan ika nagtaram nin marahay na pagdamay,',
        'Nagkamoot an aldaw sa dating pagkawaray.',
        '',
        'Dai ako namula dahil ako napildi sa kahadean,',
        'Namula ako dahil ako nahilingan nin kahalagahan;',
        'Sa kalibutan na pirming nangayo nin kalakasan,',
        'Ikaw an nagpaheling na puwede man an kalambingan.',
        '',
        'May mga taong nag-aagi siring bagyong maluya,',
        'May mga taong nag-iiwan nin sugat sa kaluluwa;',
        'Pero ika, sa tahimik mong paagi asin pag-unawa,',
        'Nag-abot siring uran na nakakapahuway sa daga.',
        '',
        'Kun haputon ninda kun taano ako napapahiyom,',
        'Dai ko masabi sa sarong sadit na pagtaramon;',
        'Ta sa lambang paglingap mo sa sakuyang kabubut-on,',
        'May hinay na bulaklak na nagbubukas sa panahon.',
        '',
        'Nasanay ako sa laban, sa bagsik, sa gerahan,',
        'Sa pagpasan nin mundo sa sakuyang abagan;',
        'Pero ika, dai mo ako ginpirit sa kadakulan,',
        'Ginpahiling mo na puwede akong mahumanay sa kahiloman.',
        '',
        'Ika an nagpaheling na dai dapat pirming matibay,',
        'Na an pagod na puso puwede man magpahuway;',
        'Na an tawo maski dakol an kaya sa buhay,',
        'Nagkakaipo man nin kamot na mag-aakay.',
        '',
        'Kun nag-aalala ka sa sakuyang pagpahinga,',
        'May init na naglalakaw sa sakuyang hininga;',
        'Ta sa simple mong pag-ataman asin pag-aruga,',
        'Nahihiling ko an bagay na haloy kong hinahanap.',
        '',
        'Kun nagagalit ka dahil dai ako nagtuturog,',
        'Dai ko nababati an galit, kundi pag-irog;',
        'Ta minsan an sermon na may kabug-at,',
        'Iyo palan an paglingap na may pag-angat.',
        '',
        'Kun sinasabi mong dapat ako mag-ingat sa lawas,',
        'Naduduman ako sa tahimik kong pagluwas;',
        'Ta may nagbabantay na sa sakuyang paghinga,',
        'Na dai ako ginagibo sanang kasangkapan.',
        '',
        'Dai ko aram kun pano ipapaliwanag an pamula,',
        'Kun pano an simpleng pag-alala nagigin musika;',
        'Pero sa lambang sandali na ika may pag-aruga,',
        'An puso kong napagal, nahihiling an pag-asa.',
        '',
        'Dai ko sanay na ako an pipilion sa kadakulan,',
        'Dai ko sanay na ako an aalagaan sa kahiloman;',
        'Kaya kun ika nag-aabot nin malinaw na kahadean,',
        'An sakuyang mukha nagigin pula sa katingalahan.',
        '',
        'Ta haloy akong naglakaw sa mga dalan nin pagduduman,',
        'Nagdadara nin mga sugat asin kalungkutan;',
        'Pero ika nag-abot na may malinig na katuyuhan,',
        'Asin dai ko aram kun pano tatanggapon an kabutihan.',
        '',
        'An puso na haloy nang nasanay sa pagpabaya,',
        'Nalilito kun inaataman na nin tama;',
        'Kaya kun ika nagiging malumoy sa sakuya,',
        'Namumula ako dahil bago an ginhawa.',
        '',
        'Dai ini pamula nin harot o kapusukan,',
        'Kundi pamula nin pusong nakahiling nin katotoohan;',
        'Na may tawo palang makakasabot sa kahinaan,',
        'Asin dai magagamit ini bilang sandatahan.',
        '',
        'Kun ako nagsasabi nin takot sa panahon,',
        'Ika dai nagtatawa sa sakuyang kabubut-on;',
        'Pigdadangog mo an mga luha kan kahiloman,',
        'Asin ginbabalot mo ini nin pag-intindihan.',
        '',
        'Kun ako napapagod sa dakulang gerahan,',
        'Ika nagigin harong sa tunga kan kalangitan;',
        'Dai mo ginpapara an sakuyang katindugan,',
        'Pero tinuturuan mo akong huminga sa kahiloman.',
        '',
        'Duman ako namumula sa tahaw kan pagduman,',
        'Ta dai ko akalaing may ganitong kahulugan;',
        'An pag-ibig palan bako sana pag-angkon,',
        'Kundi paglingap sa lambang sugat kan kabubut-on.',
        '',
        'Ika dai nag-abot para akong gamiton,',
        'Dai man para sa sugat ko magtukod nin kahadeanon;',
        'Nag-abot ka siring tawo na may paglaomon,',
        'Na handang makidangog sa sakuyang kahiloman.',
        '',
        'Kun ika nagiging mahiyain sa atubangan,',
        'Mas lalo kong nahihiling an saimong kagayunan;',
        'Ta sa lambang hiya asin mahinay na katatawanan,',
        'May bulaklak na nagtatago sa kadlagan.',
        '',
        'Kun an boses mo nag-aagi sa talinga,',
        'Baga ulap na nagdadara nin ginhawa;',
        'Dai ko napapansin na ako palan nakangisi,',
        'Ta an puso ko nakasakay sa ulap.',
        '',
        'Narurungog ko an lambing sa lambang pagtaramon,',
        'Narurungog ko man an takot sa likod kan kahiloman;',
        'Kaya imbes na lumayo sa saimong pagduduman,',
        'Mas lalo kong gustong magdanay sa harongon.',
        '',
        'Ta an saimong kahinaan dai nagpapababa sa kahalagahan,',
        'Dai man nagpapasira kan saimong katawuhan;',
        'Kun bako pa ngani, mas pinapahiling an katotoohan,',
        'Na ika tawo, mahal, asin dapat pahalagahan.',
        '',
        'Duman ako namumula, sa simpleng pagkakilala,',
        'Sa paagi mong dai nagtatago kan kaluluwa;',
        'Ta may kagayunan na dai makukua sa larawan,',
        'Kundi sa pusong naglalakaw na may katotoohan.',
        '',
        'Kun nagpadara ka nin mga larawan,',
        'Dai ko napigilan an sakuyang katingalahan;',
        'Dai dahil sa mata lamang o sa ngaran,',
        'Kundi dahil ikaw an nasa lambang larawan.',
        '',
        'Ginsave ko an mga ini sa sakuyang handumanan,',
        'Siring mga bituin sa madiklom na kalangitan;',
        'Ta kun an mundo magin mabug-at sa kahimtangan,',
        'May maheling akong rason para sa paglaoman.',
        '',
        'Pero maski dai ko maheling an saimong dagway,',
        'An saimong kabutihan nagpapadanay sa buhay;',
        'Ta an tunay na pagkagusto dai sana sa pagmasid,',
        'Kundi sa puso na dai gusto magsakit.',
        '',
        'Kun ika nag-aalala kun ako ba mapagal,',
        'An dating sugat ko nagiging mas magaan;',
        'Ta an simpleng pagtanong na may kalambingan,',
        'Nagpapahiling na ako may kahalagahan.',
        '',
        'Dai ko dapat ika ikumpara sa mga kaagihan,',
        'Pero dai ko man maitatanggi an kaibahan;',
        'Ta kun an iba nagpaheling nin kasakitan,',
        'Ika nagpaheling nin marahay na kahadean.',
        '',
        'Kun kaya ako namumula sa saimong pag-ataman,',
        'Dahil ini an dati kong haloy na ginhahanap;',
        'Dai para pagsilbihan ako sa kapalaluan,',
        'Kundi para maramdaman na ako dai pinababayaan.',
        '',
        'Ika an paalala na an gugma may kalinigan,',
        'Na an pag-ibig dai dapat puno nin kahaditan;',
        'Na puwede palang mahalin nin may paggalang,',
        'Asin pahalagahan maski sa kahinaan.',
        '',
        'Dai mo ako ginpakusog sa pilitan,',
        'Dai mo ako ginpaurag sa pagdadalagan;',
        'Hinay-hinay mo akong ginpatindog sa kahiloman,',
        'Siring kandilang binantayan sa kadikloman.',
        '',
        'Kun sinasabi mong “ako iyo” sa kahadean,',
        'An puso ko nagriribok sa kahiloman;',
        'Ta bako ini pag-angkon na may kadena,',
        'Kundi pagpili na may katotoohan.',
        '',
        'Kun ika nagigin malambing sa pagtaramon,',
        'Dai ko aram kun sain ibubutang an kabubut-on;',
        'Baga nagiging bata an pusong dating matibay,',
        'Ta sa wakas may nag-aabot nin pagdamay.',
        '',
        'An pamula ko bako dahil ako marupok,',
        'Kundi dahil an dating lamig ko nawawara;',
        'Siring yelong natutunaw sa kaadawan,',
        'Pag nag-abot an init nin kalambingan.',
        '',
        'Dai ko sanay na may maghihintay sa sakuya,',
        'Dai ko sanay na may mangangamusta sa sakuya;',
        'Kaya kun ika naghahanap kan sakuyang presensya,',
        'Namumula ako sa tahimik na tuwa.',
        '',
        'Dai ko sanay na may magtatanggol sa kahadean,',
        'Dai ko sanay na may tatanggap sa kapagalan;',
        'Kaya kun ika nagigin harong sa kagab-ihon,',
        'An sakuyang puso nagpapasalamat sa panahon.',
        '',
        'Ta an pinakamabigat na parte kan kaagihan,',
        'Bako sana sugat kundi an pag-iisahan;',
        'Pero ika nag-abot na may pagdamay,',
        'Asin tinuruan mo akong dai na mag-isahan.',
        '',
        'Kun minsan dai ko masabi an sakuyang pagkapula,',
        'Ta nahihiya man ako sa sadiring kaluluwa;',
        'Pero an katotoohan, ika an dahilan,',
        'Kun taano an puso ko nagkakaigwa nin kapayapaan.',
        '',
        'Dai ako sanay na ako an mamahalon nin tama,',
        'Dai ako sanay na ako an pipilion nin maingat;',
        'Kaya kun ika nagpapaheling nin kabutihan,',
        'An puso ko nauubusan nin panangga.',
        '',
        'Sa lambang “ingat” mo may liwanag,',
        'Sa lambang “tulog na” may paglingap;',
        'Sa lambang “kumain ka” may kahulugan,',
        'Sa lambang “nandito ako” may katibayan.',
        '',
        'Dai ko pigmamaliit an mga sadit na bagay,',
        'Ta iyan an bumubuhay sa pagod na buhay;',
        'An mga simpleng tataramon na may pagdamay,',
        'Mas makusog pa kaysa dakulang harana.',
        '',
        'Kun ako namumula, iyo an sakuyang pagsabot,',
        'Na an gugma dai pirming maingay an pag-abot;',
        'Kun minsan ini mahinay na pag-ataman,',
        'Na dai nagtataram pero puno nin kahulugan.',
        '',
        'Ika an unang nagpaheling kan pagtrato,',
        'Na dai nakakasugat, dai nakakalunod;',
        'Pagtrato na may respeto asin pag-iingat,',
        'Na sa dating buhay ko haloy kong hinahanap.',
        '',
        'Kaya kun an mukha ko namumula sa kahiloman,',
        'Dai ini kababawan o simpleng kilig lamang;',
        'Ini an pusong nakasabot sa katotoohan,',
        'Na sa wakas, may nagmahal nang may paggalang.',
        '',
        'Asin kun may maghapot kun taano ako namumula,',
        'Sasabihon ko sa tahaw kan sakuyang kaluluwa;',
        'Ta sa lambang pagtrato mong marahay sa sakuya,',
        'Nabubuhay an parte kong dati nang nawara.',
        '',
        'Kaya an pamula ko bako sana kulay,',
        'Kundi handog kan pusong nakaabot sa buhay;',
        'Ta kan tinrato mo akong tama sa kahiloman,',
        'An buong pagkatao ko natutong mamula sa kahadean.'
      ]
    },
    {
      id: 10,
      title: 'The Tide Returns',
      author: 'Anonymous',
      excerpt: ['No matter how far the tide retreats,', 'It always finds its way back to the shore—'],
      mood: 'Devoted',
      accentColor: '#1A8754',
      lines: [
        'No matter how far the tide retreats,',
        'It always finds its way back to the shore,',
        'And so my love, through all its dark defeats,',
        'Finds you and beats and swells and loves you more.',
        '',
        'The moon commands the ocean\'s endless pull,',
        'And you, somehow, command the pull of me,',
        'A gravity complete and beautiful',
        'That draws me always back across the sea.',
        '',
        'I have been a tide that tried to flee,',
        'That tried to break the pattern, find the end,',
        'But every wave comes home to where you\'d be,',
        'And I will always, always come back, friend.',
        '',
        'The tide returns — it\'s nature, it\'s the law,',
        'My heart returns to you, forever more.'
      ]
    },
    {
      id: 11,
      title: 'Burning Clouds',
      author: 'Anonymous',
      excerpt: ['The clouds were burning when I found your hand,', 'The sky a canvas no one else could paint—'],
      mood: 'Magical',
      accentColor: '#C2185B',
      lines: [
        'The clouds were burning when I found your hand,',
        'The sky a canvas no one else could paint,',
        'As if the universe had somehow planned',
        'This moment, holy, breathless, like a saint.',
        '',
        'They burned in violet, orange, pink, and rose,',
        'As though reflecting all the warmth we\'d share,',
        'The kind of beauty only heaven knows',
        'Unfolded in the evening ocean air.',
        '',
        'I could have watched the burning clouds all night',
        'But you were there and brighter than the sky,',
        'Your eyes held every color of that light',
        'And told me truths that words could not supply.',
        '',
        'The clouds burned out but I still hold your hand,',
        'The fire in my heart needs no command.'
      ]
    },
    {
      id: 12,
      title: 'Ocean Devotion',
      author: 'Anonymous',
      excerpt: ['As deep as the fathomless ocean floor,', 'As wide as the horizon in full bloom—'],
      mood: 'Eternal',
      accentColor: '#1A5276',
      lines: [
        'As deep as the fathomless ocean floor,',
        'As wide as the horizon in full bloom,',
        'My love for you grows deeper, ever more,',
        'From waking dawn to silver midnight\'s room.',
        '',
        'The ocean holds its mysteries below,',
        'In trenches where no sunlight dares to fall,',
        'And I hold secrets only you would know',
        'In depths that only you would dare to call.',
        '',
        'I am the sea: I rage, I calm, I roar,',
        'I carry ships and drown the careless soul,',
        'But you are what I\'ve always beaten for,',
        'The distant shore that makes the ocean whole.',
        '',
        'Devoted as the tides are to the moon,',
        'I love you now, forever, and too soon.'
      ]
    }
  ];

  getAllPoems(): ReadonlyArray<Poem> {
    return this.poems;
  }

  getPoem(id: number): Poem | undefined {
    return this.poems.find((poem) => poem.id === id);
  }

  getAdjacentPoems(id: number): { prev: Poem | null; next: Poem | null } {
    const idx = this.poems.findIndex((poem) => poem.id === id);

    if (idx === -1) {
      return { prev: null, next: null };
    }

    return {
      prev: idx > 0 ? this.poems[idx - 1] : null,
      next: idx < this.poems.length - 1 ? this.poems[idx + 1] : null
    };
  }

  getPoemContext(id: number): PoemContext | undefined {
    const poem = this.getPoem(id);

    if (!poem) {
      return undefined;
    }

    const { prev, next } = this.getAdjacentPoems(id);
    return {
      poem,
      prev,
      next,
      stanzas: this.buildStanzas(poem.lines)
    };
  }

  private buildStanzas(lines: ReadonlyArray<string>): string[][] {
    const stanzas: string[][] = [];
    let currentStanza: string[] = [];

    for (const line of lines) {
      if (line === '') {
        if (currentStanza.length > 0) {
          stanzas.push(currentStanza);
          currentStanza = [];
        }

        continue;
      }

      currentStanza.push(line);
    }

    if (currentStanza.length > 0) {
      stanzas.push(currentStanza);
    }

    return stanzas;
  }
}
